### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by mullenkamp** [conda-forge/fiona-feedstock#124]
Issue:
I'm getting an import error very similar to the issue I just recently opened for the netcdf4 conda-forge feedstock...sorry about this...I honestly hope it's not a major issue...
Similar to #119 and #89 

Edit: It actually appears that gdal might be the issue...as it also throws the same import error...
```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\programs\anaconda3_64bit\envs\fiona1\lib\site-packages\fiona\__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "E:\programs\anaconda3_64bit\envs\fiona1\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
```

Reproduce with:
```
conda create -n fiona1 -c conda-forge python=3.6 fiona
```

<br/>
Environment (<code>conda list</code>):
<details>

```
# packages in environment at E:\programs\anaconda3_64bit\envs\fiona1:
#
# Name                    Version                   Build  Channel
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.0               h4496350_2    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
fiona                     1.8.6            py36hce0be61_0    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      2.4.0           py36hdf5ee75_1005    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.4.3             h8408f58_1000    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1105    conda-forge
intel-openmp              2019.3                      203
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                     4_mkl    conda-forge
libcblas                  3.8.0                     4_mkl    conda-forge
libcurl                   7.64.0               h4496350_2    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.0             he26aab1_1005    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                     4_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.36            h7602738_1000    conda-forge
libpq                     11.2                 hb0bdaea_0    conda-forge
libspatialite             4.3.0a            h6a0152f_1026    conda-forge
libssh2                   1.8.1                h642c060_0    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.8             h9ce36c8_1005    conda-forge
m2w64-expat               2.1.1                         2
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gettext             0.19.7                        2
m2w64-gmp                 6.1.0                         2
m2w64-libiconv            1.14                          6
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
m2w64-xz                  5.2.2                         2
mkl                       2019.1                      144
msys2-conda-epoch         20160418                      1
munch                     2.3.2                      py_0    conda-forge
numpy                     1.16.2           py36h8078771_1    conda-forge
openjpeg                  2.3.0             h25a6d84_1003    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pip                       19.0.3                   py36_0    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h06f7779_0    conda-forge
proj4                     5.2.0             hfa6e2cd_1001    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
setuptools                40.8.0                   py36_0    conda-forge
shapely                   1.6.4           py36h8921fb9_1003    conda-forge
six                       1.12.0                py36_1000    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1000    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.33.1                   py36_0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : fiona1
    active env location : E:\programs\anaconda3_64bit\envs\fiona1
            shell level : 4
       user config file : C:\Users\michaelek\.condarc
 populated config files : C:\Users\michaelek\.condarc
          conda version : 4.6.8
    conda-build version : 3.17.8
         python version : 3.6.7.final.0
       base environment : E:\programs\anaconda3_64bit  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/mullenkamp/win-64
                          https://conda.anaconda.org/mullenkamp/noarch
                          https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : E:\programs\anaconda3_64bit\pkgs
                          C:\Users\michaelek\.conda\pkgs
                          C:\Users\michaelek\AppData\Local\conda\conda\pkgs
       envs directories : E:\programs\anaconda3_64bit\envs
                          C:\Users\michaelek\.conda\envs
                          C:\Users\michaelek\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.8 requests/2.21.0 CPython/3.6.7 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment]
This seems to be resolved by #125. Please let me know if you are still experiencing this issue.
