### ISSUE TITLE
ImportError:libgdal.so.20: undefined symbol

### ISSUE THREAD

**Issue by lastproxy** [conda-forge/fiona-feedstock#130]
Issue:
could not `import fiona` properly after `conda install -c conda-forge fiona libgdal gdal`.

Here are some shortcuts:

```
[zcx@R730XD python]$ conda install fiona geopandas gdal libgdal
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: /home/zcx/anaconda3

  added / updated specs:
    - fiona
    - gdal
    - geopandas
    - libgdal


The following NEW packages will be INSTALLED:

  fiona              conda-forge/linux-64::fiona-1.8.6-py37hf242f0b_3
  gdal               conda-forge/linux-64::gdal-2.4.1-py37hf242f0b_0
  geopandas          conda-forge/noarch::geopandas-0.5.0-py_2
  libgdal            conda-forge/linux-64::libgdal-2.4.1-hdb8f723_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
[zcx@R730XD python]$ python3 -c "import fiona"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/zcx/anaconda3/lib/python3.7/site-packages/fiona/__init__.py", line 83, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/zcx/anaconda3/lib/python3.7/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: /home/zcx/anaconda3/lib/python3.7/site-packages/fiona/../../../libgdal.so.20: undefined symbol: _ZNK6libdap5Error17get_error_messageB5cxx11Ev
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/zcx/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
_r-mutex                  1.0.0               anacondar_1
alabaster                 0.7.12                   py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.7                    py37_0
anaconda-project          0.8.2                    py37_0
asn1crypto                0.24.0                   py37_0
astroid                   2.2.5                    py37_0
astropy                   3.1.2            py37h7b6447c_0
atomicwrites              1.3.0                    py37_1
attrs                     19.1.0                   py37_1
babel                     2.6.0                    py37_0
backcall                  0.1.0                    py37_0
backports                 1.0                      py37_1
backports.os              0.1.1                    py37_0
backports.shutil_get_terminal_size 1.0.0                    py37_2
basemap                   1.2.0            py37h673bf1a_2    conda-forge
beautifulsoup4            4.7.1                    py37_1
binutils_impl_linux-64    2.31.1               h6176602_1
binutils_linux-64         2.31.1               h6176602_7
bitarray                  0.8.3            py37h14c3975_0
bkcharts                  0.2                      py37_0
blas                      1.0                         mkl
bleach                    3.1.0                    py37_0
blosc                     1.15.0               hd408876_0
bokeh                     1.0.4                    py37_0
boost-cpp                 1.68.0            h11c811c_1000    conda-forge
boto                      2.49.0                   py37_0
bottleneck                1.2.1            py37h035aef0_1
bwidget                   1.9.11                        1
bzip2                     1.0.6                h14c3975_5
ca-certificates           2019.3.9             hecc5488_0    conda-forge
cairo                     1.14.12              h8948797_3
cartopy                   0.17.0          py37h0aa2c8f_1004    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.2           py37h2e261b9_1
cftime                    1.0.3.4         py37hd352d35_1001    conda-forge
chardet                   3.0.4                    py37_1
click                     7.0                      py37_0
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.8.0                    py37_0
clyent                    1.2.2                    py37_1
colorama                  0.4.1                    py37_0
conda                     4.6.14                   py37_0    conda-forge
conda-build               3.17.8                   py37_0
conda-env                 2.6.0                         1
conda-verify              3.1.1                    py37_0
contextlib2               0.5.5                    py37_0
cryptography              2.6.1            py37h1ba5d50_0
curl                      7.64.0               hbc83047_2
cycler                    0.10.0                   py37_0
cython                    0.29.6           py37he6710b0_0
cytoolz                   0.9.0.1          py37h14c3975_1
dask                      1.1.4                    py37_1
dask-core                 1.1.4                    py37_1
dbus                      1.13.6               h746ee38_0
decorator                 4.4.0                    py37_1
defusedxml                0.5.0                    py37_1
descartes                 1.1.0                      py_3    conda-forge
distributed               1.26.0                   py37_1
docutils                  0.14                     py37_0
eccodes                   2.12.3               h4fa793d_1    conda-forge
entrypoints               0.3                      py37_0
eofs                      1.4.0                      py_0    conda-forge
et_xmlfile                1.0.1                    py37_0
expat                     2.2.6                he6710b0_0
fastcache                 1.0.2            py37h14c3975_2
filelock                  3.0.10                   py37_0
fiona                     1.8.6            py37hf242f0b_3    conda-forge
flask                     1.0.2                    py37_1
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.9.1                h8a8886c_1
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5                h7b6447c_0
future                    0.17.1                   py37_0
gcc_impl_linux-64         7.3.0                habb00fd_1    conda-forge
gcc_linux-64              7.3.0                h553295d_7    conda-forge
gdal                      2.4.1            py37hf242f0b_0    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
get_terminal_size         1.0.0                haa9412d_0
gevent                    1.4.0            py37h7b6447c_0
gfortran_impl_linux-64    7.3.0                hdf63c60_1
gfortran_linux-64         7.3.0                h553295d_7
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.56.2               hd408876_0
glob2                     0.6                      py37_1
gmp                       6.1.2                h6c8ec71_1
gmpy2                     2.0.8            py37h10f8cd9_2
graphite2                 1.3.13               h23475e2_0
greenlet                  0.4.15           py37h7b6447c_0
gsl                       2.4                  h14c3975_4
gst-plugins-base          1.14.0               hbbd80ab_1
gstreamer                 1.14.0               hb453b48_1
gxx_impl_linux-64         7.3.0                hdf63c60_1    conda-forge
gxx_linux-64              7.3.0                h553295d_7    conda-forge
h5py                      2.9.0            py37h7918eee_0
harfbuzz                  1.8.8                hffaf4a1_0
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.4               hb1b8bf9_0
heapdict                  1.0.0                    py37_2
html5lib                  1.0.1                    py37_0
icu                       58.2                 h9c2bf20_1
idna                      2.8                      py37_0
imageio                   2.5.0                    py37_0
imagesize                 1.1.0                    py37_0
importlib_metadata        0.8                      py37_0
intel-openmp              2019.3                      199
ipykernel                 5.1.0            py37h39e3cac_0
ipython                   7.4.0            py37h39e3cac_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.4.2                    py37_0
isort                     4.3.16                   py37_0
itsdangerous              1.1.0                    py37_0
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jbig                      2.1                  hdba287a_0
jdcal                     1.4                      py37_0
jedi                      0.13.3                   py37_0
jeepney                   0.4                      py37_0
jinja2                    2.10                     py37_0
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0
jupyter                   1.0.0                    py37_7
jupyter_client            5.2.4                    py37_0
jupyter_console           6.0.0                    py37_0
jupyter_core              4.4.0                    py37_0
jupyterlab                0.35.4           py37hf63ae98_0
jupyterlab_server         0.2.0                    py37_0
kealib                    1.4.10            h1978553_1003    conda-forge
keyring                   18.0.0                   py37_0
kiwisolver                1.0.1            py37hf484d3e_0
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.3.1            py37h14c3975_2
libaec                    1.0.4                hf484d3e_0    conda-forge
libarchive                3.3.3                h5d8350f_5
libcurl                   7.64.0               h20c2e04_2
libdap4                   3.19.1                        0    conda-forge
libedit                   3.1.20181209         hc058e9b_0
libffi                    3.2.1                hd88cf55_4
libgcc-ng                 8.2.0                hdf63c60_1
libgdal                   2.4.1                hdb8f723_0    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h328b03d_1009    conda-forge
liblief                   0.9.0                h7725739_2
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libpng                    1.6.36               hbc83047_0
libpq                     11.3                 h4e4e079_0    conda-forge
libsodium                 1.0.16               h1bed415_0
libspatialindex           1.9.0                he1b5a44_0    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.0                h1ba5d50_4
libstdcxx-ng              8.2.0                hdf63c60_1
libtiff                   4.0.10               h2733197_2
libtool                   2.4.6                h7b6447c_5
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13                 h1bed415_1
libxml2                   2.9.9                he19cac6_0
libxslt                   1.1.33               h7d1a2b0_0
llvmlite                  0.28.0           py37hd408876_0
locket                    0.2.0                    py37_1
lxml                      4.3.2            py37hefd8a0e_0
lz4-c                     1.8.1.2              h14c3975_0
lzo                       2.10                 h49e0be7_2
make                      4.2.1             h14c3975_2004    conda-forge
mapclassify               2.0.1                      py_0    conda-forge
markupsafe                1.1.1            py37h7b6447c_0
matplotlib                3.0.3            py37h5429711_0
matplotlib-base           3.0.3            py37h5f35d83_1    conda-forge
mccabe                    0.6.1                    py37_1
mistune                   0.8.4            py37h7b6447c_0
mkl                       2019.3                      199
mkl-service               1.1.2            py37he904b0f_5
mkl_fft                   1.0.10           py37ha843d7b_0
mkl_random                1.0.2            py37hd81dba3_0
more-itertools            6.0.0                    py37_0
mpc                       1.1.0                h10f8cd9_1
mpfr                      4.0.1                hdf1c602_3
mpmath                    1.1.0                    py37_0
msgpack-python            0.6.1            py37hfd86e86_1
multipledispatch          0.6.0                    py37_0
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.2.1                    py37_0
nbconvert                 5.4.1                    py37_3
nbformat                  4.4.0                    py37_0
ncurses                   6.1                  he6710b0_1
netcdf4                   1.4.2            py37h808af73_0
networkx                  2.2                      py37_1
nltk                      3.4                      py37_1
nose                      1.3.7                    py37_2
notebook                  5.7.8                    py37_0
numba                     0.43.1           py37h962f231_0
numexpr                   2.6.9            py37h9e4a6bb_0
numpy                     1.16.2           py37h7e9f1db_0
numpy-base                1.16.2           py37hde5b4d6_0
numpydoc                  0.8.0                    py37_0
olefile                   0.46                     py37_0
openjpeg                  2.3.1                h58a6597_0    conda-forge
openpyxl                  2.6.1                    py37_1
openssl                   1.1.1b               h14c3975_1    conda-forge
owslib                    0.17.1                     py_0    conda-forge
packaging                 19.0                     py37_0
pandas                    0.24.2           py37he6710b0_0
pandoc                    2.2.3.2                       0
pandocfilters             1.4.2                    py37_1
pango                     1.40.14              he752989_2    conda-forge
parso                     0.3.4                    py37_0
partd                     0.3.10                   py37_1
patchelf                  0.9                  he6710b0_3
path.py                   11.5.0                   py37_0
pathlib2                  2.3.3                    py37_0
patsy                     0.5.1                    py37_0
pcre                      8.43                 he6710b0_0
pep8                      1.7.1                    py37_0
pexpect                   4.6.0                    py37_0
pickleshare               0.7.5                    py37_0
pillow                    5.4.1            py37h34e0f95_0
pip                       19.0.3                   py37_0
pixman                    0.38.0               h7b6447c_0
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.9.0                    py37_0
ply                       3.11                     py37_0
poppler                   0.67.0            h2fc8fa2_1002    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.3                 hbeee2d4_0    conda-forge
proj4                     5.2.0             h14c3975_1001    conda-forge
prometheus_client         0.6.0                    py37_0
prompt_toolkit            2.0.9                    py37_0
psutil                    5.6.1            py37h7b6447c_0
ptyprocess                0.6.0                    py37_0
py                        1.8.0                    py37_0
py-lief                   0.9.0            py37h7725739_2
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37h14c3975_0
pycparser                 2.19                     py37_0
pycrypto                  2.6.1            py37h14c3975_9
pycurl                    7.43.0.2         py37h1ba5d50_0
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                    py37_0
pygments                  2.3.1                    py37_0
pygrib                    2.0.4            py37hf3f1b0b_0    conda-forge
pykdtree                  1.3.1           py37h3010b51_1002    conda-forge
pykrige                   1.4.0           py37h035aef0_1001    conda-forge
pylint                    2.3.1                    py37_0
pyodbc                    4.0.26           py37he6710b0_0
pyopenssl                 19.0.0                   py37_0
pyparsing                 2.3.1                    py37_0
pyproj                    1.9.6           py37hc0953d3_1000    conda-forge
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.14.11          py37h7b6447c_0
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.6.8                    py37_0
pytables                  3.5.1            py37h71ec239_0
pytest                    4.3.1                    py37_0
pytest-arraydiff          0.3              py37h39e3cac_0
pytest-astropy            0.5.0                    py37_0
pytest-doctestplus        0.3.0                    py37_0
pytest-openfiles          0.3.2                    py37_0
pytest-remotedata         0.3.1                    py37_0
python                    3.7.3                h0371630_0
python-dateutil           2.8.0                    py37_0
python-libarchive-c       2.8                      py37_6
pytz                      2018.9                   py37_0
pywavelets                1.0.2            py37hdd07704_0
pyyaml                    5.1              py37h7b6447c_0
pyzmq                     18.0.0           py37he6710b0_0
qt                        5.9.7                h5867ecd_1
qtawesome                 0.5.7                    py37_1
qtconsole                 4.4.3                    py37_0
qtpy                      1.7.0                    py37_1
r                         3.5.1                 r351_1000    conda-forge
r-assertthat              0.2.1            r351h6115d3f_0    conda-forge
r-backports               1.1.4            r351hcdcec82_0    conda-forge
r-base                    3.5.1             he45234b_1005    conda-forge
r-bh                      1.69.0_1         r351h6115d3f_0    conda-forge
r-boot                    1.3_22                   r351_0    conda-forge
r-class                   7.3_15          r351h96ca727_1000    conda-forge
r-cli                     1.1.0            r351h6115d3f_0    conda-forge
r-cluster                 2.0.9            r351h9bbef5b_0    conda-forge
r-codetools               0.2_16          r351h6115d3f_1000    conda-forge
r-colorspace              1.4_1            r351hcdcec82_0    conda-forge
r-crayon                  1.3.4           r351h6115d3f_1001    conda-forge
r-digest                  0.6.18          r351h96ca727_1000    conda-forge
r-dplyr                   0.8.1            r351h0357c0b_0    conda-forge
r-fansi                   0.4.0           r351h96ca727_1000    conda-forge
r-foreign                 0.8_71          r351h96ca727_1002    conda-forge
r-ggplot2                 3.1.1            r351h6115d3f_0    conda-forge
r-glue                    1.3.1            r351hcdcec82_0    conda-forge
r-gridextra               2.3             r351h6115d3f_1001    conda-forge
r-gridgraphics            0.3_0           r351h6115d3f_1001    conda-forge
r-gtable                  0.3.0            r351h6115d3f_0    conda-forge
r-kernsmooth              2.23_15         r351ha65eedd_1002    conda-forge
r-labeling                0.3             r351h6115d3f_1001    conda-forge
r-lattice                 0.20_38         r351h96ca727_1000    conda-forge
r-lazyeval                0.2.2            r351hcdcec82_0    conda-forge
r-lubridate               1.7.4           r351h29659fb_1001    conda-forge
r-magrittr                1.5             r351h6115d3f_1001    conda-forge
r-mass                    7.3_51.4         r351hcdcec82_0    conda-forge
r-matrix                  1.2_17           r351hcdcec82_0    conda-forge
r-mgcv                    1.8_28           r351hcdcec82_0    conda-forge
r-mnormt                  1.5_5           r351ha65eedd_1001    conda-forge
r-munsell                 0.5.0           r351h6115d3f_1001    conda-forge
r-nlme                    3.1_139          r351h9bbef5b_0    conda-forge
r-nnet                    7.3_12          r351h96ca727_1002    conda-forge
r-pillar                  1.4.0                h6115d3f_0    conda-forge
r-pkgconfig               2.0.2           r351h6115d3f_1001    conda-forge
r-plogr                   0.2.0           r351h6115d3f_1001    conda-forge
r-plyr                    1.8.4           r351h29659fb_1002    conda-forge
r-psych                   1.8.12           r351h6115d3f_0    conda-forge
r-purrr                   0.3.2            r351hcdcec82_0    conda-forge
r-r6                      2.4.0            r351h6115d3f_0    conda-forge
r-rcolorbrewer            1.1_2           r351h6115d3f_1001    conda-forge
r-rcpp                    1.0.1            r351h0357c0b_0    conda-forge
r-recommended             3.5.1                 r351_1001    conda-forge
r-reshape2                1.4.3           r351h29659fb_1003    conda-forge
r-rlang                   0.3.4            r351hcdcec82_0    conda-forge
r-rpart                   4.1_15           r351hcdcec82_0    conda-forge
r-scales                  1.0.0           r351h29659fb_1001    conda-forge
r-spatial                 7.3_11          r351h96ca727_1002    conda-forge
r-stringi                 1.4.3            r351h0357c0b_0    conda-forge
r-stringr                 1.4.0            r351h6115d3f_0    conda-forge
r-survival                2.44_1.1         r351hcdcec82_0    conda-forge
r-tibble                  2.1.1            r351hcdcec82_0    conda-forge
r-tidyr                   0.8.3            r351h0357c0b_0    conda-forge
r-tidyselect              0.2.5           r351h29659fb_1000    conda-forge
r-utf8                    1.1.4           r351h96ca727_1000    conda-forge
r-vctrs                   0.1.0           r351h96ca727_1000    conda-forge
r-viridislite             0.3.0           r351h6115d3f_1001    conda-forge
r-withr                   2.1.2           r351h6115d3f_1000    conda-forge
r-zeallot                 0.1.0           r351h6115d3f_1000    conda-forge
r-zoo                     1.8_5            r351hcdcec82_0    conda-forge
readline                  7.0                  h7b6447c_5
requests                  2.21.0                   py37_0
rope                      0.12.0                   py37_0
rtree                     0.8.3           py37h666c49c_1002    conda-forge
ruamel_yaml               0.15.46          py37h14c3975_0
scikit-image              0.14.2           py37he6710b0_0
scikit-learn              0.20.3           py37hd81dba3_0
scipy                     1.2.1            py37h7c811a0_0
seaborn                   0.9.0                    py37_0
secretstorage             3.1.1                    py37_0
send2trash                1.5.0                    py37_0
setuptools                40.8.0                   py37_0
shapely                   1.6.4           py37h2afed24_1004    conda-forge
simplegeneric             0.8.1                    py37_2
singledispatch            3.4.0.3                  py37_0
sip                       4.19.8           py37hf484d3e_0
six                       1.12.0                   py37_0
snappy                    1.1.7                hbae5bb6_3
snowballstemmer           1.2.1                    py37_0
sortedcollections         1.1.2                    py37_0
sortedcontainers          2.1.0                    py37_0
soupsieve                 1.8                      py37_0
sphinx                    1.8.5                    py37_0
sphinxcontrib             1.0                      py37_1
sphinxcontrib-websupport  1.1.0                    py37_1
spyder                    3.3.3                    py37_0
spyder-kernels            0.4.2                    py37_0
sqlalchemy                1.3.1            py37h7b6447c_0
sqlite                    3.27.2               h7b6447c_0
statsmodels               0.9.0            py37h035aef0_0
sympy                     1.3                      py37_0
tblib                     1.3.2                    py37_0
terminado                 0.8.1                    py37_1
testpath                  0.4.2                    py37_0
tk                        8.6.9             h84994c4_1001    conda-forge
tktable                   2.10                 h14c3975_0
toolz                     0.9.0                    py37_0
tornado                   6.0.2            py37h7b6447c_0
tqdm                      4.31.1                   py37_1
traitlets                 4.3.2                    py37_0
tzcode                    2018g             h14c3975_1001    conda-forge
unicodecsv                0.14.1                   py37_0
unixodbc                  2.3.7                h14c3975_0
urllib3                   1.24.1                   py37_0
util-linux                2.21                          0
wcwidth                   0.1.7                    py37_0
webencodings              0.5.1                    py37_1
werkzeug                  0.14.1                   py37_0
wheel                     0.33.1                   py37_0
widgetsnbextension        3.4.2                    py37_0
wrapt                     1.11.1           py37h7b6447c_0
wurlitzer                 1.0.2                    py37_0
xerces-c                  3.2.2             hac72e42_1001    conda-forge
xlrd                      1.2.0                    py37_0
xlsxwriter                1.1.5                    py37_0
xlwt                      1.3.0                    py37_0
xz                        5.2.4                h14c3975_4
yaml                      0.1.7                had09818_2
zeromq                    4.3.1                he6710b0_3
zict                      0.1.4                    py37_0
zipp                      0.3.3                    py37_1
zlib                      1.2.11               h7b6447c_3
zstd                      1.3.7                h0b5b093_0
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : None
            shell level : 0
       user config file : /home/zcx/.condarc
 populated config files : /home/zcx/.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : /home/zcx/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /home/zcx/anaconda3/pkgs
                          /home/zcx/.conda/pkgs
       envs directories : /home/zcx/anaconda3/envs
                          /home/zcx/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Linux/2.6.32-754.6.3.el6.x86_64 centos/6.10 glibc/2.12
                UID:GID : 517:518
             netrc file : /home/zcx/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
Looking at your package list I see a typical mix of channel. Please see https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it
