### ISSUE TITLE
fiona 1.8.6 py36hf242f0b_3 ogrext.cpython-36m-x86_64-linux-gnu.so has a libnsl.so.1 requirement

### ISSUE THREAD

**Issue by akrherz** [conda-forge/fiona-feedstock#138]
Issue: ldd inspecting ogrext.cpython-36m-x86_64-linux-gnu.so shows a libnsl.so.1 requirement not provided by conda-forge?

I am unsure if this is a valid problem or not, but figured I would post it.  I have found that fiona needs the `libnsl` RPM installed on RHEL8 to properly run.  It is unclear to me if conda-forge should be providing this library or some other infrastructure in conda-forge should see this missing library:

```
$ ldd ogrext.cpython-36m-x86_64-linux-gnu.so | grep nsl
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fec67964000)
```

Thank you, as always, for the help and wonderful work on this project.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /opt/miniconda3/envs/prod:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.12                     py_0    conda-forge
alembic                   1.1.0                      py_0    conda-forge
apiclient                 1.0.3                    pypi_0    pypi
appdirs                   1.4.3                      py_1    conda-forge
arm_pyart                 1.10.1           py36hd352d35_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
aspy.yaml                 1.3.0                      py_0    conda-forge
astroid                   2.2.5                    py36_0    conda-forge
async_generator           1.10                       py_0    conda-forge
atk                       2.32.0               haf93ef1_0    conda-forge
atomicwrites              1.3.0                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
automat                   0.7.0                    pypi_0    pypi
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bcrypt                    3.1.6            py36h516909a_1    conda-forge
beautifulsoup4            4.8.0                    py36_0    conda-forge
bitstring                 3.1.5                    pypi_0    pypi
black                     19.3b0                     py_0    conda-forge
blas                      2.12                   openblas    conda-forge
bleach                    3.1.0                      py_0    conda-forge
blinker                   1.4                        py_1    conda-forge
bokeh                     1.3.4                    py36_0    conda-forge
boost-cpp                 1.70.0               ha2d47e9_1    conda-forge
boxsdk                    1.5.5                    pypi_0    pypi
bzip2                     1.0.8                h516909a_0    conda-forge
ca-certificates           2019.6.16            hecc5488_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cachetools                2.1.0                    pypi_0    pypi
cairo                     1.16.0            ha4e643d_1000    conda-forge
cartopy                   0.17.0          py36h0aa2c8f_1004    conda-forge
cdo                       1.9.6             hd104f1c_1006    conda-forge
cdsapi                    0.1.3                    pypi_0    pypi
certifi                   2019.6.16                py36_1    conda-forge
certipy                   0.1.3                      py_0    conda-forge
cf_units                  2.0.1           py36h3010b51_1002    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
cfgrib                    0.9.7.1                    py_0    conda-forge
cfgv                      2.0.1                      py_0    conda-forge
cftime                    1.0.3.4         py36hd352d35_1001    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               1.2.1                      py_0    conda-forge
cmarkgfm                  0.4.2            py36h14c3975_2    conda-forge
codecov                   2.0.15                   pypi_0    pypi
configurable-http-proxy   4.1.0                  node11_1    conda-forge
consistent-hash-git       0.3                      pypi_0    pypi
constantly                15.1.0                     py_0    conda-forge
coverage                  4.5.4            py36h516909a_0    conda-forge
coveralls                 1.8.2                      py_0    conda-forge
cryptography              2.7              py36h72c5cf5_0    conda-forge
curl                      7.65.3               hf8cf82a_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.13          py36he1b5a44_0    conda-forge
cytoolz                   0.10.0           py36h516909a_0    conda-forge
dask                      2.3.0                      py_0    conda-forge
dask-core                 2.3.0                      py_0    conda-forge
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
descartes                 1.1.0                      py_3    conda-forge
distributed               2.3.2                      py_1    conda-forge
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.15.2                   py36_0    conda-forge
dropbox                   9.4.0                      py_0    conda-forge
eccodes                   2.12.3               h4fa793d_1    conda-forge
ecmwf_grib                1.14.7                        2    conda-forge
editdistance              0.5.3            py36hf484d3e_0    conda-forge
entrypoints               0.3                   py36_1000    conda-forge
ephem                     3.7.7.0          py36h516909a_0    conda-forge
esmf                      7.1.0             h9eb252b_1005    conda-forge
esmpy                     7.1.0            py36h24bf2e0_3    conda-forge
et_xmlfile                1.0.1                   py_1001    conda-forge
expat                     2.2.5             he1b5a44_1003    conda-forge
feedgen                   0.7.0                    pypi_0    pypi
fftw                      3.3.8           nompi_h7f3a6c3_1109    conda-forge
fiona                     1.8.6            py36hf242f0b_3    conda-forge
flake8                    3.7.8                    py36_1    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_1    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
fribidi                   1.0.5             h516909a_1002    conda-forge
fsspec                    0.4.3                      py_0    conda-forge
future                    0.16.0                   pypi_0    pypi
g2clib                    1.6.0                hf3f1b0b_9    conda-forge
gdal                      2.4.1            py36hf242f0b_0    conda-forge
gdata                     3.0.0                    pypi_0    pypi
gdk-pixbuf                2.36.12           h7a26e22_1003    conda-forge
geographiclib             1.49                       py_0    conda-forge
geojson                   2.5.0                      py_0    conda-forge
geopandas                 0.5.1                      py_0    conda-forge
geopy                     1.20.0                     py_0    conda-forge
geos                      3.7.1             hf484d3e_1000    conda-forge
geotiff                   1.4.3             h1105359_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
ghostscript               9.22              hf484d3e_1001    conda-forge
giflib                    5.1.7                h516909a_1    conda-forge
glib                      2.58.3            h6f030ca_1002    conda-forge
gobject-introspection     1.58.2          py36h5503ade_1002    conda-forge
google-api-python-client  1.7.4                    pypi_0    pypi
google-auth               1.5.0                    pypi_0    pypi
google-auth-httplib2      0.0.3                    pypi_0    pypi
graphite2                 1.3.13            hf484d3e_1000    conda-forge
graphviz                  2.40.1               h5933667_1    conda-forge
gsl                       2.4               h294904e_1006    conda-forge
gst-plugins-base          1.14.5               h0935bb2_0    conda-forge
gstreamer                 1.14.5               h36ae1b5_0    conda-forge
h5netcdf                  0.7.4                      py_0    conda-forge
h5py                      2.9.0           nompi_py36hcafd542_1103    conda-forge
harfbuzz                  2.4.0                h37c48d4_1    conda-forge
hdf4                      4.2.13            h9a582f1_1002    conda-forge
hdf5                      1.10.4          nompi_h3c11f04_1106    conda-forge
hdfeos2                   2.20              h64bfcee_1000    conda-forge
hdfeos5                   5.1.16               hccfc538_4    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
httplib2                  0.11.3                   pypi_0    pypi
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
identify                  1.4.7                      py_0    conda-forge
idna                      2.8                   py36_1000    conda-forge
iembot                    0.1.0                    pypi_0    pypi
imageio                   2.5.0                    py36_0    conda-forge
imagemagick               7.0.8_63        pl526h51306e4_0    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
importlib_metadata        0.20                     py36_0    conda-forge
importlib_resources       1.0.2                 py36_1000    conda-forge
incremental               17.5.0                     py_0    conda-forge
inotify                   0.2.10                   pypi_0    pypi
intel-openmp              2019.4                      243  
ipykernel                 5.1.2            py36h5ca1d4c_0    conda-forge
ipython                   7.8.0            py36h5ca1d4c_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
isort                     4.3.21                   py36_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jbig                      2.1               h14c3975_2001    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.15.1                   py36_0    conda-forge
jenks                     1.0                      pypi_0    pypi
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
json5                     0.8.5                      py_0    conda-forge
jsonschema                3.0.2                    py36_0    conda-forge
jupyter_client            5.3.1                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterhub                1.0.0                    py36_0    conda-forge
jupyterlab                1.1.1                      py_0    conda-forge
jupyterlab_server         1.0.6                      py_0    conda-forge
kealib                    1.4.10            h1978553_1003    conda-forge
keras                     2.2.4                    pypi_0    pypi
keras-applications        1.0.7                    pypi_0    pypi
keras-preprocessing       1.0.9                    pypi_0    pypi
kiwisolver                1.1.0            py36hc9558a2_0    conda-forge
krb5                      1.16.3            h05b26f9_1001    conda-forge
lazy-object-proxy         1.4.2            py36h516909a_0    conda-forge
libaec                    1.0.4                hf484d3e_0    conda-forge
libblas                   3.8.0               12_openblas    conda-forge
libcblas                  3.8.0               12_openblas    conda-forge
libcroco                  0.6.13               h8d621e5_0    conda-forge
libcurl                   7.65.3               hda55be3_0    conda-forge
libdap4                   3.19.1            hd48c02d_1000    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.4.1                hdb8f723_0    conda-forge
libgfortran-ng            7.2.0                hdf63c60_3    conda-forge
libiconv                  1.15              h516909a_1005    conda-forge
libkml                    1.3.0             h4fcabce_1010    conda-forge
liblapack                 3.8.0               12_openblas    conda-forge
liblapacke                3.8.0               12_openblas    conda-forge
libnetcdf                 4.6.2             hbdf4f91_1001    conda-forge
libopenblas               0.3.7                h6e990d7_1    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libpq                     11.5                 hd9ab2ff_1    conda-forge
libprotobuf               3.9.1                h8b12597_0    conda-forge
librsvg                   2.44.14              h68f2853_2    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libspatialindex           1.9.0                he1b5a44_1    conda-forge
libspatialite             4.3.0a            hb5ec416_1026    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.10            h57b8799_1003    conda-forge
libtool                   2.4.6             h14c3975_1002    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h99fbfcb_2    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_2    conda-forge
libxslt                   1.1.32            hae48121_1003    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.4.1            py36h7ec2d77_0    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
lzo                       2.10              h14c3975_1000    conda-forge
m2r                       0.2.1                      py_0    conda-forge
mako                      1.1.0                      py_0    conda-forge
mapscript                 7.3.0                    pypi_0    pypi
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                3.1.0                    py36_1    conda-forge
matplotlib-base           3.1.0            py36hfd891ef_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
metar                     1.6.0                    pypi_0    pypi
metpy                     0.10.2                   py36_0    conda-forge
mistune                   0.8.4           py36h14c3975_1000    conda-forge
mkl                       2019.4                      243  
mock                      3.0.5                    py36_0    conda-forge
mod-wsgi                  4.6.4                    pypi_0    pypi
more-itertools            7.2.0                      py_0    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1             hc99cbb1_1014    conda-forge
msgpack-python            0.6.1            py36h6bb024c_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.6.0                    py36_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncl                       6.6.2                h9ce15c7_1    conda-forge
nco                       4.8.0                hfb3d286_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
netcdf-fortran            4.4.5             hea25ff8_1000    conda-forge
netcdf4                   1.5.1.2          py36had58050_0    conda-forge
nodeenv                   1.3.3                      py_0    conda-forge
nodejs                    11.14.0              he1b5a44_1    conda-forge
nose                      1.3.7                 py36_1002    conda-forge
notebook                  6.0.1                    py36_0    conda-forge
numexpr                   2.7.0            py36hb3f55d8_0    conda-forge
numpy                     1.17.1           py36h95a1406_0    conda-forge
nwnserver                 0.2                      pypi_0    pypi
oauth                     1.0.1                    pypi_0    pypi
oauth2client              4.1.2                    pypi_0    pypi
oauthlib                  3.0.1                      py_0    conda-forge
odfpy                     1.3.6                    pypi_0    pypi
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                h58a6597_0    conda-forge
openpyxl                  2.6.3                      py_0    conda-forge
openssl                   1.1.1c               h516909a_0    conda-forge
ossuuid                   1.6.2             hf484d3e_1000    conda-forge
owslib                    0.18.0                     py_0    conda-forge
packaging                 19.0                       py_0    conda-forge
pamela                    1.0.0                      py_0    conda-forge
pamqp                     2.3.0                    pypi_0    pypi
pandas                    0.25.1           py36hb3f55d8_0    conda-forge
pandoc                    2.7.3                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               ha030887_1    conda-forge
parso                     0.5.1                      py_0    conda-forge
partd                     1.0.0                      py_0    conda-forge
paste                     3.1.1                    py36_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
perl                      5.26.2            h516909a_1006    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pika                      1.1.0                      py_0    conda-forge
pillow                    6.1.0            py36h6b7be26_1    conda-forge
pint                      0.9                      py36_2    conda-forge
pip                       19.2.3                   py36_0    conda-forge
pixman                    0.34.0            h14c3975_1003    conda-forge
pkg-config                0.29.2            h14c3975_1005    conda-forge
pkginfo                   1.5.0.1                    py_0    conda-forge
pluggy                    0.12.0                     py_0    conda-forge
pockets                   0.6.2                    pypi_0    pypi
pooch                     0.5.2                    py36_0    conda-forge
poppler                   0.67.0               ha967d66_7    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.5                 hc63931a_1    conda-forge
pre_commit                1.18.1                   py36_0    conda-forge
proj4                     5.2.0             he1b5a44_1006    conda-forge
prometheus_client         0.7.1                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
protobuf                  3.9.1            py36he1b5a44_0    conda-forge
psutil                    5.6.3            py36h516909a_0    conda-forge
psycopg2                  2.8.3            py36h72c5cf5_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
py                        1.8.0                      py_0    conda-forge
pyasn1                    0.4.6                      py_0    conda-forge
pyasn1-modules            0.2.6                      py_0    conda-forge
pybufrkit                 0.2.7                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pycurl                    7.43.0.2         py36h16ce93b_1    conda-forge
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pygrib                    2.0.4            py36hf3f1b0b_0    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyiem                     0.12.0                   pypi_0    pypi
pyjwt                     1.7.1                      py_0    conda-forge
pykdtree                  1.3.1           py36h3010b51_1002    conda-forge
pyldm                     0.1.0                    pypi_0    pypi
pylint                    2.3.1                    py36_0    conda-forge
pyngl                     1.6.1            py36h24fcaf0_1    conda-forge
pynio                     1.5.5            py36h8b983ae_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pypandoc                  1.4                      pypi_0    pypi
pyparsing                 2.4.2                      py_0    conda-forge
pyproj                    1.9.6           py36h516909a_1002    conda-forge
pyqt                      5.9.2            py36hcca6a23_2    conda-forge
pyrsistent                0.15.4           py36h516909a_0    conda-forge
pyrss2gen                 1.1                      pypi_0    pypi
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
pytest                    5.1.2                    py36_0    conda-forge
pytest-cov                2.7.1                      py_0    conda-forge
pytest-mpl                0.10                       py_0    conda-forge
pytest-runner             5.1                        py_0    conda-forge
python                    3.6.7             h357f687_1005    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-editor             1.0.4                      py_0    conda-forge
python-memcached          1.59                       py_0    conda-forge
python-twitter            3.4.2                    pypi_0    pypi
pytz                      2019.2                     py_0    conda-forge
pyyaml                    5.1.2            py36h516909a_0    conda-forge
pyzmq                     18.0.2           py36h1768529_2    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
rabbitpy                  2.0.0                    pypi_0    pypi
rasterio                  1.0.25           py36hdff7cfa_0    conda-forge
rasterstats               0.13.1                     py_1    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
readme_renderer           24.0                       py_0    conda-forge
reportlab                 3.5.23           py36h7d98c4e_0    conda-forge
requests                  2.22.0                   py36_1    conda-forge
requests-oauthlib         1.2.0                      py_0    conda-forge
requests-toolbelt         0.9.1                      py_0    conda-forge
rrdtool                   0.1.14                   pypi_0    pypi
rsa                       3.4.2                    pypi_0    pypi
rtree                     0.8.3           py36h666c49c_1002    conda-forge
scikit-learn              0.19.2                   pypi_0    pypi
scipy                     1.3.1            py36h921218d_2    conda-forge
seaborn                   0.9.0                      py_1    conda-forge
send2trash                1.5.0                      py_0    conda-forge
service_identity          18.1.0                     py_0    conda-forge
setuptools                41.2.0                   py36_0    conda-forge
setuptools-markdown       0.2                      pypi_0    pypi
shapely                   1.6.4           py36h06cd6f9_1005    conda-forge
simplejson                3.16.1           py36h470a237_0    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
siphon                    0.8.0                 py36_1001    conda-forge
six                       1.12.0                py36_1000    conda-forge
smartsheet-python-sdk     1.3.4.dev3+ga1559f8          pypi_0    pypi
snowballstemmer           1.9.0                      py_0    conda-forge
snuggs                    1.4.6                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
soupsieve                 1.9.3                    py36_0    conda-forge
sphinx                    2.2.0                      py_0    conda-forge
sphinx-gallery            0.4.0                    py36_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-napoleon    0.6.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlalchemy                1.3.8            py36h516909a_0    conda-forge
sqlite                    3.29.0               hcee41ef_1    conda-forge
statsmodels               0.10.1           py36hc1659b7_0    conda-forge
tblib                     1.4.0                      py_0    conda-forge
tempest-remap             2.0.3                h5f743cb_1    conda-forge
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
textgenrnn                1.5.0                    pypi_0    pypi
tk                        8.6.9             hed695b0_1002    conda-forge
tlslite                   0.4.9                    pypi_0    pypi
toml                      0.9.4                    pypi_0    pypi
toolz                     0.10.0                     py_0    conda-forge
tornado                   6.0.3            py36h516909a_0    conda-forge
tox                       3.4.0                    pypi_0    pypi
tqdm                      4.35.0                     py_0    conda-forge
traitlets                 4.3.2                 py36_1000    conda-forge
trmm_rsl                  1.49                          3    conda-forge
twine                     1.13.0                     py_1    conda-forge
twisted                   19.7.0           py36h516909a_1    conda-forge
twittytwister             0.1.3                    pypi_0    pypi
twython                   3.7.0                      py_0    conda-forge
txyam2                    0.5.1+weasyl.2           pypi_0    pypi
typed-ast                 1.4.0            py36h516909a_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
udunits2                  2.2.27.6          h4e0c4b3_1001    conda-forge
unidecode                 1.0.22                   pypi_0    pypi
unixodbc                  2.3.7             h227dcee_1000    conda-forge
uritemplate               3.0.0                      py_1    conda-forge
urllib3                   1.25.3                   py36_0    conda-forge
verde                     0.0.1a0+72.g9ae9091          pypi_0    pypi
virtualenv                16.0.0                   pypi_0    pypi
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.6                   py36_0    conda-forge
windrose                  1.6                      pypi_0    pypi
wordcloud                 1.5.0           py36h14c3975_1000    conda-forge
wrapt                     1.11.2           py36h516909a_0    conda-forge
wrf-python                1.3.2            py36h7eb8c7e_1    conda-forge
xarray                    0.12.3                     py_0    conda-forge
xerces-c                  3.2.2             hea5cb30_1003    conda-forge
xesmf                     0.2.0                    py36_0    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xlsxwriter                1.2.0                      py_0    conda-forge
xlwt                      1.3.0                      py_1    conda-forge
xorg-imake                1.0.7                         0    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.8                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxaw               1.0.13            h14c3975_1002    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxmu               1.1.3                h516909a_0    conda-forge
xorg-libxpm               3.5.12            h516909a_1002    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-libxt                1.1.5             h516909a_1003    conda-forge
xorg-makedepend           1.0.6                he1b5a44_1    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zict                      1.0.0                      py_0    conda-forge
zipp                      0.6.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1005    conda-forge
zope.interface            4.6.0           py36h14c3975_1000    conda-forge
zstd                      1.4.0                h3b9ef0a_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : prod
    active env location : /opt/miniconda3/envs/prod
            shell level : 1
       user config file : /home/akrherz/.condarc
 populated config files : /home/akrherz/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /opt/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/miniconda3/pkgs
                          /home/akrherz/.conda/pkgs
       envs directories : /opt/miniconda3/envs
                          /home/akrherz/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.6.7 Linux/4.18.0-80.7.2.el8_0.x86_64 rhel/8.0 glibc/2.28
                UID:GID : 43306:101
             netrc file : /home/akrherz/.netrc
           offline mode : False

```
</details>

**Comment by ocefpaf** [comment]
Looks like `libnsl` should be in `glibc` and that is expected to be in the user system. However, I just found: https://github.com/AppImage/pkg2appimage/issues/336

We need an strategy for this. Thanks for reporting it.

**Comment by anitagraser** [comment]
I'm trying to conda install from conda-forge on Windows 10 (`conda-forge/win-64::fiona-1.8.9.post2-py37h3234bc7_0`) and also run into issues with fiona.ogrext:

```
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: Das angegebene Modul wurde nicht gefunden.
```

The error doesn't state which DLL cannot be found but it might be related.

**Comment by WeatherGod** [comment]
Ping? This is an issue on CentOS 8. Just built the environment with all the latest packages last week.

**Comment by akrherz** [comment]
Appears to still be the case for me, `fiona==1.8.13 py38h033e0f6_1`

```
ldd ./envs/prod/lib/python3.8/site-packages/fiona/ogrext.cpython-38-x86_64-linux-gnu.so | grep nsl
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fdfed6a2000)
```

**Comment by WeatherGod** [comment]
On CentOS 8, looks like a sufficient work-around is to `sudo yum install libnsl`, which will install the legacy compatibility library.

**Comment by akrherz** [comment]
Just to denote that this issue still appears to be valid `fiona==1.8.18 py38h37fbd03_0`

```
$ ldd ./envs/prod/lib/python3.8/site-packages/fiona/ogrext.cpython-38-x86_64-linux-gnu.so | grep nsl
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007fc55c73a000)
```

**Comment by philippemiron** [comment]
Any solution for this?

**Comment by akrherz** [comment]
> Any temporary solution for this?

If you are on RHEL/Centos8, `dnf install libnsl`

**Comment by ocefpaf** [comment]
Also, `libnsl` was just added as a conda package. So you can `conda install -c conda-forge libnsl` now too. I'm on the fence if we should make it a fiona/rasterio dependency b/c it sounds like an overkill.

**Comment by datapythonista** [comment]
> Also, `libnsl` was just added as a conda package. So you can `conda install -c conda-forge libnsl` now too. I'm on the fence if we should make it a fiona/rasterio dependency b/c it sounds like an overkill.

I did try that, and it didn't work, not sure why:
```
(fiona) [mgarcia@xps ibis-omniscidb]$ conda install -c conda-forge libnsl
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /home/mgarcia/miniconda3/envs/fiona

  added / updated specs:
    - libnsl


The following NEW packages will be INSTALLED:

  libnsl             conda-forge/linux-64::libnsl-2.0.0-h7f98852_0


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(fiona) [mgarcia@xps]$ python
Python 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:20:46) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mgarcia/miniconda3/envs/fiona/lib/python3.9/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/mgarcia/miniconda3/envs/fiona/lib/python3.9/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libnsl.so.1: cannot open shared object file: No such file or directory
```

**Comment by WeatherGod** [comment]
fiona would need to be "built against" conda's version of libnsl. By
default, the libraries installed in conda are not usually found by the OS
for dynamic linking (this is actually a good thing and helps segregate the
conda environment from the rest of the system).

**Comment by philippemiron** [comment]
On Fedora, there is this [fiona package](https://fedora.pkgs.org/34/fedora-x86_64/python3-fiona-1.8.13-5.fc33.x86_64.rpm.html), which has no `libnsl.so.1` dependency. Still, once installed, you can `import fiona` without issue with the system python3... but inside a conda environment it doesn't work. I'm a bit confused.

**Comment by WeatherGod** [comment]
I would be curious to know what the Fedora maintainers did to completely
cut libnsl out of the dependency tree in many packages. For a long time,
libnsl was just simply a part of the mainline glibc, so many packages just
linked it just because it was there and available. I don't think fiona and
other conda packages explicitly depended on libnsl, but rather depended
upon another library that had a dependency (whether it was needed or not)
to it.

**Comment by isuruf** [comment]
@ocefpaf, since python will bring in `libnsl` anyways, it's good if `fiona` added `libnsl` to `host` dependencies so that fiona links to `libnsl.so.2` from the conda package instead of the glibc one.

**Comment by izahn** [comment]
I cannot reproduce this issue in a fedora docker with a newly created environment pulling in the most recent python build. @datapythonista @akrherz can you still reproduce it with any of the most recent conda-forge python builds?

**Comment by akrherz** [comment]
> can you still reproduce it with any of the most recent conda-forge python builds?

My centos 8 stream linux64 env has `1.8.20=py38hbb147eb_1` and
```
$ ldd ./lib/python3.8/site-packages/fiona/ogrext.cpython-38-x86_64-linux-gnu.so| grep nsl
libnsl.so.3 => /opt/miniconda3/envs/prod/./lib/python3.8/site-packages/fiona/../../../././libnsl.so.3 (0x00007f6f42251000)
```

**Comment by izahn** [comment]
> On Fedora, there is this [fiona package](https://fedora.pkgs.org/34/fedora-x86_64/python3-fiona-1.8.13-5.fc33.x86_64.rpm.html), which has no `libnsl.so.1` dependency. Still, once installed, you can `import fiona` without issue with the system python3... but inside a conda environment it doesn't work. I'm a bit confused.

On Fedora 33 `python` itself depends on `libnsl`. Since 2021-10-12 conda-forge `python` also depends on `libnsl`. AFAIK this now works in conda-forge exactly as it does in Fedora. @philippemiron can you still reproduce any problem with the most recent conda-forge python builds?

**Comment by izahn** [comment]
> > can you still reproduce it with any of the most recent conda-forge python builds?
> 
> My centos 8 stream linux64 env has `1.8.20=py38hbb147eb_1` and
> 
> ```
> $ ldd ./lib/python3.8/site-packages/fiona/ogrext.cpython-38-x86_64-linux-gnu.so| grep nsl
> libnsl.so.3 => /opt/miniconda3/envs/prod/./lib/python3.8/site-packages/fiona/../../../././libnsl.so.3 (0x00007f6f42251000)
> ```

So all good right?

**Comment by ocefpaf** [comment]
> @ocefpaf, since python will bring in `libnsl` anyways, it's good if `fiona` added `libnsl` to `host` dependencies so that fiona links to `libnsl.so.2` from the conda package instead of the glibc one.

That should happen probably in gdal but I guess we are covered now, right?

**Comment by izahn** [comment]
I believe there is no direct gdal dependency on nsl; gdal depends on xerces-c which depends on nsl. We have already built xerces-c against conda-forge libnsl in https://github.com/conda-forge/xerces-c-feedstock/pull/30 so I do not believe anything further is needed.
