### ISSUE TITLE
ImportError on macOS after libtiff update

### ISSUE THREAD

**Issue by martinfleis** [conda-forge/fiona-feedstock#158]
Issue:

Installing Fiona in a fresh environment on macOS will result in ImportError on `import fiona`. That is likely caused by the recent update of libtiff (2 days ago). See the Traceback below.

edit: the issue is not present on ubuntu.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/martin/anaconda3/envs/fiona/lib/python3.8/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/martin/anaconda3/envs/fiona/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/martin/anaconda3/envs/fiona/lib/python3.8/site-packages/fiona/ogrext.cpython-38-darwin.so, 2): Library not loaded: @rpath/libwebp.7.dylib
  Referenced from: /Users/martin/anaconda3/envs/fiona/lib/libtiff.5.dylib
  Reason: Incompatible library version: libtiff.5.dylib requires version 9.0.0 or later, but libwebp.7.dylib provides version 8.0.0
```

<br/>
Environment (<code>conda list</code>):

<details>

```
$ conda list
# Name                    Version                   Build  Channel
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.72.0               hdf9ef73_0    conda-forge
bzip2                     1.0.8                h0b31af3_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hec6a9b0_1003    conda-forge
certifi                   2019.11.28       py38h32f6830_1    conda-forge
cfitsio                   3.470                h84d2f63_2    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.68.0               h8754def_0    conda-forge
expat                     2.2.9                h4a8c4bd_2    conda-forge
fiona                     1.8.13           py38he71f6a4_0    conda-forge
fontconfig                2.13.1            h6b1039f_1001    conda-forge
freetype                  2.10.1               h8da9a1a_0    conda-forge
freexl                    1.0.5             h1de35cc_1002    conda-forge
gdal                      3.0.4            py38h9f7df5a_2    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.5.1                h4bdff65_9    conda-forge
gettext                   0.19.8.1          h46ab8bc_1002    conda-forge
giflib                    5.2.1                h0b31af3_2    conda-forge
glib                      2.58.3          py38h338c551_1003    conda-forge
hdf4                      4.2.13            h84186c3_1003    conda-forge
hdf5                      1.10.5          nompi_h3e39495_1104    conda-forge
icu                       64.2                 h6de7cb9_1    conda-forge
jpeg                      9c                h1de35cc_1001    conda-forge
json-c                    0.13.1            h1de35cc_1001    conda-forge
kealib                    1.4.12               h2324030_0    conda-forge
krb5                      1.16.4               h1752a42_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.68.0               h709d2b2_0    conda-forge
libcxx                    9.0.1                         1    conda-forge
libdap4                   3.20.4               habf5908_0    conda-forge
libedit                   3.1.20170329      hcfe32e1_1001    conda-forge
libffi                    3.2.1             h4a8c4bd_1007    conda-forge
libgdal                   3.0.4                hbf8f8d6_2    conda-forge
libgfortran               4.0.0                         2    conda-forge
libiconv                  1.15              h0b31af3_1006    conda-forge
libkml                    1.3.0             h169b8f9_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libnetcdf                 4.7.3           nompi_hda4e5f1_101    conda-forge
libopenblas               0.3.9                h3d69b6c_0    conda-forge
libpng                    1.6.37               hbbe82c9_1    conda-forge
libpq                     12.2                 h554dc5a_0    conda-forge
libspatialite             4.3.0a            hbcd37d4_1037    conda-forge
libssh2                   1.8.2                hcdc9a53_2    conda-forge
libtiff                   4.1.0                h2ae36a8_5    conda-forge
libwebp                   1.0.2                hd3bf737_5    conda-forge
libwebp-base              1.1.0                         2    conda-forge
libxml2                   2.9.10               h53d96d6_0    conda-forge
llvm-openmp               9.0.1                h28b9765_2    conda-forge
lz4-c                     1.8.3             h6de7cb9_1001    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               h0a44026_1002    conda-forge
numpy                     1.18.1           py38hde6bac1_0    conda-forge
openjpeg                  2.3.1                h254dc36_3    conda-forge
openssl                   1.1.1e               h0b31af3_0    conda-forge
pcre                      8.44                 h4a8c4bd_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h01d97ff_1003    conda-forge
poppler                   0.67.0               h16886b5_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 h16d8c28_0    conda-forge
proj                      6.3.1                h773a61f_1    conda-forge
python                    3.8.2           hdc38147_4_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hcfe32e1_0    conda-forge
setuptools                46.0.0           py38h32f6830_2    conda-forge
shapely                   1.7.0            py38h5b1fbde_2    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               h93121df_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hd5e958f_2    conda-forge
tk                        8.6.10               hbbe82c9_0    conda-forge
tzcode                    2019a             h01d97ff_1002    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8f8adb3_1004    conda-forge
xz                        5.2.4             h1de35cc_1001    conda-forge
zlib                      1.2.11            h0b31af3_1006    conda-forge
zstd                      1.4.4                hed8d7c8_2    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
active environment : fiona
    active env location : /Users/martin/anaconda3/envs/fiona
            shell level : 7
       user config file : /Users/martin/.condarc
 populated config files : /Users/martin/.condarc
          conda version : 4.8.2
    conda-build version : 3.18.9
         python version : 3.6.9.final.0
       virtual packages : __osx=10.15.3
       base environment : /Users/martin/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/udst/osx-64
                          https://conda.anaconda.org/udst/noarch
          package cache : /Users/martin/anaconda3/pkgs
                          /Users/martin/.conda/pkgs
       envs directories : /Users/martin/anaconda3/envs
                          /Users/martin/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.6.9 Darwin/19.3.0 OSX/10.15.3
                UID:GID : 501:20
             netrc file : None
           offline mode : False

```
</details>

**Comment by martinfleis** [comment]
Fixed in upstream.
