### ISSUE TITLE
Incompatibility with new libnetcdf version?

### ISSUE THREAD

**Issue by mathause** [conda-forge/fiona-feedstock#159]
Issue:
Trying to `import fiona` in a brand new environment yields the following error:

```python
import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mathause/conda/envs/test_fiona/lib/python3.8/site-packages/fiona/__init__.py", line 84, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/home/mathause/conda/envs/test_fiona/lib/python3.8/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libnetcdf.so.15: cannot open shared object file: No such file or directory
```

I created the test environment like so:
```
conda create --name test_fiona python fiona
```

Note that libnetcdf was recently (today 29. March 2020 (or on the 28, depending on your time zone ;))) updated: https://anaconda.org/conda-forge/libnetcdf

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /home/mathause/conda/envs/test_fiona:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
attrs                     19.3.0                     py_0    conda-forge
boost-cpp                 1.72.0               h8e57a91_0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2019.11.28       py38h32f6830_1    conda-forge
cfitsio                   3.470                hb60a0a2_2    conda-forge
click                     7.1.1              pyh8c360ce_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.68.0               hf8cf82a_0    conda-forge
expat                     2.2.9                he1b5a44_2    conda-forge
fiona                     1.8.13           py38h900e953_0    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.1               he06d7ca_0    conda-forge
freexl                    1.0.5             h14c3975_1002    conda-forge
gdal                      3.0.4            py38h172510d_2    conda-forge
geos                      3.8.1                he1b5a44_0    conda-forge
geotiff                   1.5.1                hcbe54f9_9    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
giflib                    5.2.1                h516909a_2    conda-forge
glib                      2.58.3          py38h73cb85d_1003    conda-forge
hdf4                      4.2.13            hf30be14_1003    conda-forge
hdf5                      1.10.5          nompi_h3c11f04_1104    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
json-c                    0.13.1            h14c3975_1001    conda-forge
kealib                    1.4.12               hec59c27_0    conda-forge
krb5                      1.16.4               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_0    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.68.0               hda55be3_0    conda-forge
libdap4                   3.20.4               hd3bb157_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgdal                   3.0.4                hce44138_2    conda-forge
libgfortran-ng            7.3.0                hdf63c60_5    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
libkml                    1.3.0             hb574062_1011    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libnetcdf                 4.7.4           nompi_h9f9fd6a_100    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libpq                     12.2                 hae5116b_0    conda-forge
libspatialite             4.3.0a            heb269f5_1037    conda-forge
libssh2                   1.8.2                h22169c7_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc3755c2_3    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp                   1.0.2                h56121f0_5    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               9.0.1                hc9558a2_2    conda-forge
lz4-c                     1.8.3             he1b5a44_1001    conda-forge
munch                     2.5.0                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
numpy                     1.18.1           py38h8854b6b_1    conda-forge
openjpeg                  2.3.1                h981e76c_3    conda-forge
openssl                   1.1.1e               h516909a_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
poppler                   0.67.0               h14e79db_8    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                12.2                 hf1211e9_0    conda-forge
proj                      6.3.1                hc80f0dc_1    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
python                    3.8.2           h8356626_5_cpython    conda-forge
python_abi                3.8                      1_cp38    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
setuptools                46.1.3           py38h32f6830_0    conda-forge
shapely                   1.7.0            py38hd168ffb_2    conda-forge
six                       1.14.0                     py_1    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
tbb                       2018.0.5             h2d50403_0    conda-forge
tiledb                    1.7.0                hcde45ca_2    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tzcode                    2019a             h516909a_1002    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xerces-c                  3.2.2             h8412b87_1004    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.4             h516909a_1002    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h3b9ef0a_2    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : test_fiona
    active env location : /home/mathause/conda/envs/test_fiona
            shell level : 2
       user config file : /home/mathause/.condarc
 populated config files : /home/mathause/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __glibc=2.27
       base environment : /home/mathause/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/mathause/conda/pkgs
                          /home/mathause/.conda/pkgs
       envs directories : /home/mathause/conda/envs
                          /home/mathause/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Linux/4.15.0-91-generic linuxmint/19.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by mathause** [comment]
Note that pinning the libnetcdf version fixes the problem

```
conda create --name test_fiona python fiona libnetcdf=4.7.3
```

**Comment by jorisvandenbossche** [comment]
cc @ocefpaf

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/gdal-feedstock/pull/372

I already pulled the latest `libnetcdf` and I'm working on a migrator and re-pin to avoid this again in the future.

**Comment by jorisvandenbossche** [comment]
Thanks a lot @ocefpaf !
