### ISSUE TITLE
missing libLerc.4.dylib

### ISSUE THREAD

**Issue by andrewpcone** [conda-forge/fiona-feedstock#199]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

I have a shared library `@rpath/libLerc.dylib`, but I don't have `@rpath/libLerc.4.dylib` that seems required. When I try to use fiona, I get:
```
Python 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:43:44) [Clang 13.0.1 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/og/opt/anaconda3/envs/osgeo/lib/python3.10/site-packages/fiona/__init__.py", line 86, in <module>
    from fiona.collection import BytesCollection, Collection
  File "/Users/og/opt/anaconda3/envs/osgeo/lib/python3.10/site-packages/fiona/collection.py", line 11, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/Users/og/opt/anaconda3/envs/osgeo/lib/python3.10/site-packages/fiona/ogrext.cpython-310-darwin.so, 2): Library not loaded: @rpath/libLerc.4.dylib
  Referenced from: /Users/og/opt/anaconda3/envs/osgeo/lib/libgdal.31.dylib
  Reason: image not found
```

### Installed packages

```shell
# Name                    Version                   Build  Channel
affine                    2.3.0              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
blas                      1.0                         mkl  
blosc                     1.21.1               h97e831e_3    conda-forge
boost-cpp                 1.78.0               h8b082ac_1    conda-forge
brotlipy                  0.7.0           py310hca72f7f_1002  
bzip2                     1.0.8                h1de35cc_0  
c-ares                    1.18.1               hca72f7f_0  
ca-certificates           2022.10.11           hecd8cb5_0  
cairo                     1.16.0               h691a603_2  
certifi                   2022.9.24       py310hecd8cb5_0  
cffi                      1.15.1          py310hc55c11b_0  
cfitsio                   4.1.0                h2c97ad1_0    conda-forge
charset-normalizer        2.0.4              pyhd3eb1b0_0  
click                     8.0.4           py310hecd8cb5_0  
click-plugins             1.1.1              pyhd3eb1b0_0  
cligj                     0.7.2              pyhd3eb1b0_0  
conda                     22.9.0          py310hecd8cb5_0  
conda-package-handling    1.9.0           py310hca72f7f_1  
cryptography              38.0.1          py310hf6deb26_0  
curl                      7.85.0               hca72f7f_0  
expat                     2.4.9                he9d5cce_0  
fiona                     1.8.22          py310h5a14c0a_0    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hd3eb1b0_0  
font-ttf-inconsolata      2.001                hcb22688_0  
font-ttf-source-code-pro  2.030                hd3eb1b0_0  
font-ttf-ubuntu           0.83                 h8b1ccd4_0  
fontconfig                2.14.1               h5bb23bf_0    conda-forge
fonts-anaconda            1                    h8fa9717_0  
fonts-conda-ecosystem     1                    hd3eb1b0_0  
freetype                  2.12.1               hd8bbffd_0  
freexl                    1.0.6                h9ed2024_0  
gdal                      3.5.2           py310he22d2f2_0    conda-forge
geos                      3.11.0               hb486fe8_0    conda-forge
geotiff                   1.7.1                ha1a2aeb_3    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                haf1e3a3_0  
glib                      2.74.1               hbc0c0cd_0    conda-forge
glib-tools                2.74.1               hbc0c0cd_0    conda-forge
hdf4                      4.2.15               h0623a88_4    conda-forge
hdf5                      1.12.2          nompi_hc782337_100    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.4             py310hecd8cb5_0  
intel-openmp              2021.4.0          hecd8cb5_3538  
jpeg                      9e                   hca72f7f_0  
json-c                    0.16                 hca72f7f_0  
kealib                    1.4.15               h51f5cc1_1    conda-forge
krb5                      1.19.3               hb49756b_0    conda-forge
lcms2                     2.12                 hf1fd2bf_0  
lerc                      3.0                  he9d5cce_0  
libcurl                   7.85.0               h6dfd666_0  
libcxx                    14.0.6               h9765a3e_0  
libdap4                   3.20.6               h3e144a0_2    conda-forge
libdeflate                1.8                  h9ed2024_5  
libedit                   3.1.20210910         hca72f7f_0  
libev                     4.33                 h9ed2024_1  
libffi                    3.4.2                he9d5cce_4  
libgdal                   3.5.2                hcf5fda6_0    conda-forge
libgfortran               5.0.0           11_3_0_hecd8cb5_28  
libgfortran5              11.3.0              h9dfd629_28  
libglib                   2.74.1               h3ba3332_0    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libkml                    1.3.0             haeb80ef_1015    conda-forge
libnetcdf                 4.8.1           nompi_hebd45d5_104    conda-forge
libnghttp2                1.46.0               ha29bfda_0  
libpng                    1.6.37               ha441bb4_0  
libpq                     14.5                 h50fae06_1    conda-forge
librttopo                 1.1.0               he07d8f5_11    conda-forge
libspatialite             5.0.1               h611af13_19    conda-forge
libsqlite                 3.39.4               ha978bb4_0    conda-forge
libssh2                   1.10.0               h0a4fc7d_0  
libtiff                   4.4.0                h2ef1027_0  
libwebp-base              1.2.4                hca72f7f_0  
libxml2                   2.10.3               hb9e07b5_0    conda-forge
libzip                    1.9.2                h3ad4413_1    conda-forge
libzlib                   1.2.13               hfd90126_4    conda-forge
llvm-openmp               14.0.6               h0dcd299_0  
lz4-c                     1.9.3                h23ab428_1  
mkl                       2021.4.0           hecd8cb5_637  
mkl-service               2.4.0           py310hca72f7f_0  
mkl_fft                   1.3.1           py310hf879493_0  
mkl_random                1.2.2           py310hc081a56_0  
munch                     2.5.0              pyhd3eb1b0_0  
ncurses                   6.3                  hca72f7f_3  
nspr                      4.33                 he9d5cce_0  
nss                       3.78                 ha8197d3_0    conda-forge
numpy                     1.23.3          py310hc1140d4_0  
numpy-base                1.23.3          py310h2a77c02_0  
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openssl                   1.1.1q               hca72f7f_0  
pcre                      8.45                 h23ab428_0  
pcre2                     10.37                he7042d7_1  
pip                       22.2.2          py310hecd8cb5_0  
pixman                    0.40.0               h9ed2024_1  
poppler                   22.04.0              h9d9b264_3    conda-forge
poppler-data              0.4.11               hecd8cb5_0  
postgresql                14.5                 h7bc2cb3_1    conda-forge
proj                      9.0.1                h05f0992_1    conda-forge
pycosat                   0.6.3           py310hca72f7f_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9           py310hecd8cb5_0  
pysocks                   1.7.1           py310hecd8cb5_0  
python                    3.10.6          ha7b0be1_0_cpython    conda-forge
python_abi                3.10                    2_cp310    conda-forge
rasterio                  1.3.3           py310heddb795_0    conda-forge
rasterstats               0.14.0                     py_0  
readline                  8.2                  hca72f7f_0  
requests                  2.28.1          py310hecd8cb5_0  
ruamel_yaml               0.15.100        py310hca72f7f_0  
setuptools                63.4.1          py310hecd8cb5_0  
shapely                   1.8.5           py310hd79a494_1    conda-forge
simplejson                3.17.6          py310hca72f7f_0  
six                       1.16.0             pyhd3eb1b0_1  
snappy                    1.1.9                he9d5cce_0  
snuggs                    1.4.7              pyhd3eb1b0_0  
sqlite                    3.39.3               h707629a_0  
tiledb                    2.11.3               h3b7b576_1    conda-forge
tk                        8.6.12               h5d9f67b_0  
toolz                     0.11.2             pyhd3eb1b0_0  
tqdm                      4.64.1          py310hecd8cb5_0  
tzcode                    2022e                hb7f2c08_0    conda-forge
tzdata                    2022e                h04d1e81_0  
urllib3                   1.26.12         py310hecd8cb5_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xerces-c                  3.2.4                h2007e90_0    conda-forge
xz                        5.2.6                hca72f7f_0  
yaml                      0.2.5                haf1e3a3_0  
zlib                      1.2.13               hfd90126_4    conda-forge
zstd                      1.5.2                hcb37349_0
```

### Environment info

```shell
active environment : osgeo
    active env location : /Users/og/opt/anaconda3/envs/osgeo
            shell level : 2
       user config file : /Users/og/.condarc
 populated config files : /Users/og/.condarc
          conda version : 22.9.0
    conda-build version : 3.18.11
         python version : 3.7.6.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/og/opt/anaconda3  (writable)
      conda av data dir : /Users/og/opt/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/og/opt/anaconda3/pkgs
                          /Users/og/.conda/pkgs
       envs directories : /Users/og/opt/anaconda3/envs
                          /Users/og/.conda/envs
               platform : osx-64
             user-agent : conda/22.9.0 requests/2.22.0 CPython/3.7.6 Darwin/20.6.0 OSX/10.16
                UID:GID : 501:20
             netrc file : /Users/og/.netrc
           offline mode : False
```

**Comment by akrherz** [comment]
It appears that you are mixing `conda-forge` and `defaults` channel content, which will fail in manners like this.  You need to have `conda-forge` first and strict channel priority see [tips and tricks](https://conda-forge.org/docs/user/tipsandtricks.html)

**Comment by wealloveicey** [comment]
Hi, have you solved the problem now? I came across the same problem and have struggled for hours.

**Comment by ocefpaf** [comment]
> Hi, have you solved the problem now? I came across the same problem and have struggled for hours.

Please open a new issue with the require debug info @wealloveicey . If you are mixing channels too like the original poster, just read the message above. Closing this and locking the issue so folks here open new ones with the require info for us to debug.
