### ISSUE TITLE
ImportError: libproj.so.9

### ISSUE THREAD

**Issue by dennissergeev** [conda-forge/fiona-feedstock#29]
I've just noticed that `fiona` fails to import in Anaconda environment on Ubuntu with conda-forge as the priority channel:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/local/fwv14jru/anaconda3/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/local/fwv14jru/anaconda3/lib/python3.5/site-packages/fiona/collection.py", line 8, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libproj.so.9: cannot open shared object file: No such file or directory
```
Here's what my environment looks like:
```
# packages in environment at /local/fwv14jru/anaconda3:
#
alabaster                 0.7.9                    py35_0    conda-forge
altair                    1.0.0                    py35_0    conda-forge
anaconda                  custom                   py35_0  
anaconda-client           1.5.1                    py35_0    conda-forge
anaconda-navigator        1.2.3                    py35_0  
apptools                  4.4.0                    py35_0    conda-forge
argcomplete               1.0.0                    py35_1  
arrow                     0.8.0                    py35_0    conda-forge
arrow                     0.8.0                     <pip>
astropy                   1.1.2               np110py35_0  
babel                     2.3.4                    py35_0    conda-forge
backports.shutil_get_terminal_size 1.0.0                    py35_0    conda-forge
basemap                   1.0.8.dev0          np110py35_3    conda-forge
basemap-data-hires        1.0.8.dev0                    2    conda-forge
beautifulsoup4            4.5.1                    py35_0  
biggus                    0.14.0                   py35_1    conda-forge
binaryornot               0.4.0                     <pip>
binaryornot               0.4.0                    py35_1    conda-forge
bitarray                  0.8.1                    py35_0  
blas                      1.1                    openblas    conda-forge
blaze                     0.10.1                   py35_0  
blinker                   1.4                      py35_0    conda-forge
bokeh                     0.12.3                   py35_0  
boto                      2.43.0                   py35_0  
boto3                     1.4.1                    py35_0    conda-forge
botocore                  1.4.49                   py35_0    conda-forge
bottleneck                1.2.0               np110py35_0    conda-forge
ca-certificates           2016.9.26                     0    conda-forge
cached-property           1.3.0                     <pip>
cairo                     1.12.18                       8    conda-forge
cartopy                   0.14.3              np110py35_3    conda-forge
certifi                   2016.9.26                py35_0    conda-forge
cf_units                  1.1.3                    py35_0    conda-forge
cffi                      1.9.1                    py35_0  
chardet                   2.3.0                    py35_0  
chardet                   2.3.0                     <pip>
chest                     0.2.3                    py35_0  
click                     6.6                      py35_0    conda-forge
click-plugins             1.0.3                    py35_0    conda-forge
cligj                     0.4.0                    py35_0  
cloudpickle               0.2.1                    py35_2    conda-forge
clyent                    1.2.1                    py35_0    conda-forge
colorama                  0.3.7                    py35_0    conda-forge
conda                     4.2.13                   py35_0    conda-forge
conda-build               2.0.11                   py35_0  
conda-env                 2.6.0                         0    conda-forge
conda-manager             0.4.0                    py35_0  
conda-verify              2.0.0                    py35_0  
configobj                 5.0.6                    py35_0  
cookiecutter              1.4.0                    py35_1    conda-forge
cryptography              1.6                      py35_0  
curl                      7.49.1                        1    conda-forge
cycler                    0.10.0                   py35_0    conda-forge
cyordereddict             1.0.0                    py35_1    conda-forge
cython                    0.25.1                   py35_0    conda-forge
cytoolz                   0.8.0                    py35_0    conda-forge
dask                      0.12.0                   py35_0    conda-forge
datashape                 0.5.2                    py35_0  
decorator                 4.0.10                   py35_0    conda-forge
descartes                 1.0.2                    py35_0    conda-forge
dill                      0.2.5                    py35_0    conda-forge
distributed               1.14.3                   py35_0    conda-forge
docopt                    0.6.2                     <pip>
docutils                  0.12                     py35_0    conda-forge
dynd-python               0.7.2                    py35_0  
DyPy                      0.1                       <pip>
entrypoints               0.2.2                    py35_0    conda-forge
envisage                  4.5.1                    py35_0    conda-forge
et_xmlfile                1.0.1                    py35_0  
expat                     2.1.0                         2    conda-forge
faamtools                 0.2.3                     <pip>
fastcache                 1.0.2                    py35_1  
feedgenerator             1.9                      py35_0    conda-forge
filelock                  2.0.6                    py35_0    conda-forge
fiona                     1.7.1               np110py35_0    conda-forge
flake8                    3.2.1                    py35_0    conda-forge
flask                     0.11.1                   py35_0    conda-forge
flask-cors                3.0.2                    py35_0    conda-forge
flexx                     0.4.1                    py35_0    conda-forge
folium                    0.2.1                    py35_0    conda-forge
fontconfig                2.11.1                        3    conda-forge
freeglut                  2.8.1                         0  
freetype                  2.6.3                         1    conda-forge
freexl                    1.0.2                         1    conda-forge
future                    0.15.2                   py35_0    conda-forge
future                    0.15.2                    <pip>
gdal                      2.1.2               np110py35_2    conda-forge
geopandas                 0.2.1                    py35_2    conda-forge
geos                      3.5.1                         1    conda-forge
geoviews                  1.1.0                    py35_0    ioam
gettext                   0.19.7                        1    conda-forge
gevent                    1.1.2                    py35_0  
ghost.py                  0.2.3                    py35_0    conda-forge
ghp-import                0.4.1                    py35_0    conda-forge
giflib                    5.1.4                         0    conda-forge
glib                      2.48.0                        4    conda-forge
glue-vispy-viewers        0.6                      py35_0    conda-forge
glueviz                   0.9.1                    py35_0    conda-forge
greenlet                  0.4.10                   py35_0  
h5netcdf                  0.3.1                    py35_0    conda-forge
h5py                      2.6.0               np110py35_7    conda-forge
harfbuzz                  1.0.6                         0    conda-forge
hdf4                      4.2.12                        0    conda-forge
hdf5                      1.8.17                        7    conda-forge
heapdict                  1.0.0                    py35_0    conda-forge
holoviews                 1.6.2                    py35_0    conda-forge
icu                       56.1                          4    conda-forge
idna                      2.1                      py35_0    conda-forge
imageio                   1.5                       <pip>
imagesize                 0.7.1                    py35_0    conda-forge
ipykernel                 4.5.1                    py35_0    conda-forge
ipython                   5.1.0                    py35_1    conda-forge
ipython_genutils          0.1.0                    py35_0    conda-forge
ipywidgets                5.2.2                    py35_2    conda-forge
iris                      1.10.0                   py35_0    conda-forge
itsdangerous              0.24                     py35_0    conda-forge
jbig                      2.1                           0  
jdcal                     1.3                      py35_0  
jedi                      0.9.0                    py35_0    conda-forge
jinja2                    2.8                      py35_1    conda-forge
jinja2-time               0.1.0                    py35_0    conda-forge
jinja2-time               0.2.0                     <pip>
jmespath                  0.9.0                    py35_0    conda-forge
jpeg                      9b                            0    conda-forge
JSAnimation               0.1                       <pip>
json-c                    0.12                          0    conda-forge
jsoncpp                   0.10.6                        1    conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter                   1.0.0                    py35_3  
jupyter-contrib-core      0.3.0                     <pip>
jupyter-nbextensions-configurator 0.2.1                     <pip>
jupyter_client            4.4.0                    py35_0    conda-forge
jupyter_console           5.0.0                    py35_0    conda-forge
jupyter_contrib_core      0.3.0                    py35_0    conda-forge
jupyter_contrib_nbextensions 0.2.1                    py35_0    conda-forge
jupyter_core              4.2.0                    py35_0    conda-forge
jupyter_nbextensions_configurator 0.2.2                    py35_0    conda-forge
jupyterlab                0.10.0                   py35_0    conda-forge
kealib                    1.4.6                         3    conda-forge
krb5                      1.14.2                        0    conda-forge
lancet                    0.9.0                    py35_0  
LatLon23                  1.0.7                     <pip>
libdap4                   3.18.2                        0    conda-forge
libdynd                   0.7.2                         0  
libffi                    3.2.1                         2    conda-forge
libgcc                    5.2.0                         0  
libgfortran               3.0.0                         1  
libiconv                  1.14                          3    conda-forge
libmo_unpack              3.0                           1    conda-forge
libnetcdf                 4.4.1.1                       0    conda-forge
libpng                    1.6.26                        0    conda-forge
libpq                     9.5.4                         3    conda-forge
libsodium                 1.0.10                        0    conda-forge
libspatialindex           1.8.5                         1    conda-forge
libspatialite             4.3.0a                        8    conda-forge
libtiff                   4.0.6                         7    conda-forge
libuuid                   1.0.3                         1    conda-forge
libxml2                   2.9.4                         3    conda-forge
libxslt                   1.1.29                        1    conda-forge
lightning-python          1.2.1                     <pip>
livereload                2.5.0                    py35_0    conda-forge
llvmlite                  0.11.0                   py35_0  
locket                    0.2.0                    py35_1    conda-forge
lxml                      3.6.4                    py35_0    conda-forge
markdown                  2.6.7                    py35_0  
Markdown                  2.6.6                     <pip>
markupsafe                0.23                     py35_0    conda-forge
matplotlib                1.5.3               np110py35_2    conda-forge
mayavi                    4.5.0                    py35_0    menpo
mccabe                    0.5.0                    py35_0    conda-forge
metpy                     0.4.2                    py35_0    conda-forge
mistune                   0.7.3                    py35_0    conda-forge
mkdocs                    0.16.0                   py35_0    conda-forge
mkdocs-bootstrap          0.1.1                    py35_0    conda-forge
mkdocs-bootswatch         0.4.0                    py35_0    conda-forge
mkl                       11.3.3                        0  
mkl-rt                    11.1                         p0  
mkl-service               1.1.2                    py35_2  
mo_pack                   0.2.0               np110py35_0    conda-forge
mock                      2.0.0                    py35_0    conda-forge
moviepy                   0.2.2.11                  <pip>
mpmath                    0.19                     py35_0    conda-forge
msgpack-python            0.4.8                    py35_0    conda-forge
multipledispatch          0.4.8                    py35_0    conda-forge
munch                     2.0.4                    py35_0    conda-forge
nb_config_manager         0.1.3                    py35_0  
nbbrowserpdf              0.2.2                    py35_0    anaconda-nb-extensions
nbconvert                 4.2.0                    py35_0    conda-forge
nbformat                  4.1.0                    py35_0    conda-forge
nbpresent                 3.0.2                    py35_1    conda-forge
nc_time_axis              1.0.0                    py35_0    conda-forge
ncurses                   5.9                           9    conda-forge
netcdf4                   1.2.4               np110py35_2    conda-forge
networkx                  1.11                     py35_0    conda-forge
nltk                      3.2.1                    py35_0    conda-forge
nose                      1.3.7                    py35_2    conda-forge
notebook                  4.2.3                    py35_0    conda-forge
numba                     0.26.0              np110py35_0  
numexpr                   2.6.1               np110py35_0    conda-forge
numpy                     1.10.4          py35_blas_openblas_204  [blas_openblas]  conda-forge
odo                       0.5.0                    py35_1  
openblas                  0.2.18                        6    conda-forge
openjpeg                  2.1.2                         1    conda-forge
openpyxl                  2.4.0                    py35_0  
openssl                   1.0.2h                        2    conda-forge
owslib                    0.13.0                   py35_0    conda-forge
palettable                2.1.1                     <pip>
pandas                    0.19.1              np110py35_0    conda-forge
pango                     1.40.1                        0    conda-forge
param                     1.3.2                    py35_0  
partd                     0.3.6                    py35_0  
patchelf                  0.9                           1    conda-forge
path.py                   8.2.1                    py35_0    conda-forge
patsy                     0.4.1                    py35_0    conda-forge
pbr                       1.10.0                   py35_0    conda-forge
pcre                      8.38                          1    conda-forge
pelican                   3.6.3                     <pip>
pep8                      1.7.0                    py35_0    conda-forge
pexpect                   4.2.1                    py35_0    conda-forge
pickleshare               0.7.3                    py35_0    conda-forge
pillow                    3.4.2                    py35_0    conda-forge
pint                      0.7.2                    py35_2    conda-forge
pip                       9.0.1                    py35_0    conda-forge
pixman                    0.34.0                        0    conda-forge
pkginfo                   1.2.1                    py35_0    conda-forge
plotly                    1.12.10                  py35_0    conda-forge
ply                       3.9                      py35_0  
postgresql                9.5.4                         2    conda-forge
poyo                      0.4.0                     <pip>
poyo                      0.3.0                    py35_0    conda-forge
proj.4                    4.9.3                         0    conda-forge
proj4                     4.9.3                         1    conda-forge
prompt_toolkit            1.0.9                    py35_0    conda-forge
protobuf                  3.0.0                    py35_0    conda-forge
psutil                    4.3.0                    py35_0    conda-forge
psycopg2                  2.6.2                    py35_1    conda-forge
ptyprocess                0.5.1                    py35_0    conda-forge
py                        1.4.31                   py35_0    conda-forge
pyasn1                    0.1.9                    py35_0    conda-forge
pycodestyle               2.2.0                    py35_0    conda-forge
pycosat                   0.6.1                    py35_0    conda-forge
pycparser                 2.17                     py35_0    conda-forge
pycrypto                  2.6.1                    py35_0    conda-forge
pycurl                    7.43.0                   py35_0  
pyepsg                    0.3.1                    py35_0    conda-forge
pyface                    5.1.0                    py35_0    conda-forge
pyflakes                  1.2.3                    py35_0    conda-forge
pygments                  2.1.3                    py35_1    conda-forge
pyke                      1.1.1                    py35_0    conda-forge
pyopengl                  3.1.1a1             np110py35_0  
pyopenssl                 16.0.0                   py35_0    conda-forge
pyparsing                 2.1.10                   py35_0    conda-forge
pypdf2                    1.26.0                   py35_1    conda-forge
pyproj                    1.9.5.1                  py35_0    conda-forge
pyqt                      4.11.4                   py35_1    conda-forge
pysal                     1.12.0                   py35_0    conda-forge
pyshp                     1.2.10                   py35_0    conda-forge
pytables                  3.3.0               np110py35_0    conda-forge
pytest                    3.0.4                    py35_0    conda-forge
python                    3.5.2                         3    conda-forge
python-dateutil           2.6.0                    py35_0    conda-forge
python-decorator          4.0.10                   py35_0    conda-forge
python-simplegeneric      0.8.1                    py35_0    conda-forge
pytube                    6.1.10                    <pip>
pytz                      2016.7                   py35_0    conda-forge
pyyaml                    3.11                     py35_0    conda-forge
pyzmq                     16.0.2                   py35_0    conda-forge
qt                        4.8.7                         3    conda-forge
qtawesome                 0.3.3                    py35_0    conda-forge
qtconsole                 4.2.1                    py35_0    conda-forge
qtpy                      1.1.1                    py35_0    conda-forge
readline                  6.2                           0    conda-forge
redis                     3.2.0                         0  
redis-py                  2.10.5                   py35_0    conda-forge
requests                  2.12.1                   py35_0    conda-forge
rope                      0.10.3                   py35_0  
rtree                     0.8.2                    py35_0    conda-forge
ruamel_yaml               0.11.14                  py35_0  
s3fs                      0.0.7                    py35_0    conda-forge
s3transfer                0.1.8                    py35_0    conda-forge
sattools                  0.1                       <pip>
scikit-image              0.12.3              np110py35_0    conda-forge
scikit-learn              0.18            np110py35_blas_openblas_202  [blas_openblas]  conda-forge
scipy                     0.18.1          np110py35_blas_openblas_200  [blas_openblas]  conda-forge
setproctitle              1.1.10                   py35_0    conda-forge
setuptools                29.0.1                   py35_0    conda-forge
shapely                   1.5.17              np110py35_1    conda-forge
simplegeneric             0.8.1                    py35_0    conda-forge
simplekml                 1.3.0                    py35_0    conda-forge
singledispatch            3.4.0.3                  py35_0    conda-forge
sip                       4.18                     py35_0    conda-forge
siphon                    0.4.0                    py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
snowballstemmer           1.2.1                    py35_0    conda-forge
sockjs-tornado            1.0.3                    py35_0  
sphinx                    1.4.8                    py35_0    conda-forge
sphinx_rtd_theme          0.1.9                    py35_0    conda-forge
spyder                    2.3.9                    py35_1    conda-forge
sqlalchemy                1.1.4                    py35_0  
sqlite                    3.13.0                        1    conda-forge
statsmodels               0.6.1               np110py35_0    conda-forge
sympy                     1.0                      py35_0    conda-forge
tblib                     1.3.0                    py35_0  
terminado                 0.6                      py35_0    conda-forge
tk                        8.5.19                        0    conda-forge
toolz                     0.8.0                    py35_0    conda-forge
tornado                   4.4.2                    py35_0    conda-forge
tqdm                      4.7.4                     <pip>
traitlets                 4.3.0                    py35_0    conda-forge
traits                    4.6.0                    py35_1    conda-forge
traitsui                  5.1.0                    py35_0    conda-forge
udunits2                  2.2.20                        1    conda-forge
unicodecsv                0.14.1                   py35_0  
unidecode                 0.04.19                  py35_0    conda-forge
util-linux                2.21                          0  
vega                      0.4.4                    py35_0    conda-forge
vincent                   0.4.4                    py35_0    conda-forge
vispy                     0.4.0.106.gf8a69d0     np110py35_0  
vtk                       7.1.0                    py35_0    conda-forge
wcwidth                   0.1.7                    py35_0    conda-forge
werkzeug                  0.11.10                  py35_0    conda-forge
wheel                     0.29.0                   py35_0    conda-forge
whichcraft                0.4.0                    py35_0    conda-forge
whichcraft                0.4.0                     <pip>
widgetsnbextension        1.2.6                    py35_3    conda-forge
xarray                    0.8.2                    py35_0    conda-forge
xerces-c                  3.1.4                         2    conda-forge
xlrd                      1.0.0                    py35_0  
xlsxwriter                0.9.3                    py35_0  
xlwt                      1.1.2                    py35_0  
xonsh                     0.4.7                    py35_1    conda-forge
xray                      0.7.0                    py35_0  
xz                        5.2.2                         0    conda-forge
yaml                      0.1.6                         0    conda-forge
zeromq                    4.1.5                         0    conda-forge
zict                      0.1.0                    py35_0    conda-forge
zlib                      1.2.8                         3    conda-forge
```
Is there any way to fix it?

Installing fiona into a separate environment (`conda create -n TEST -c conda-forge python=3.5 fiona --yes`) works, but I was wondering if it's possible to fix it in my root environment. I can see `libproj.so.9` in `~/anaconda3/pkgs/proj.4-4.9.2-0/lib/`.

**Comment by ocefpaf** [comment]
> Is there any way to fix it?

Not sure if there is a way to do in your root env. (And that is not
recommended as you loose the init of the env vars.)

> Installing fiona into a separate environment (conda create -n TEST -c
conda-forge python=3.5 fiona --yes) works, but I was wondering if it's
possible to fix it in my root environment. I can see libproj.so.9 in
~/anaconda3/pkgs/proj.4-4.9.2-0/lib/.

That is because conda's doesn't need to satisfy all the packages installed
by default in the anaconda root.

I always recommend miniconda and the use of envs. More stable and
reproducible work flow.

**Comment by dennissergeev** [comment]
Thanks for advice! I was feeling that my root environment is a bit of a mess (though kudos to conda-forge for making it possible to have so many packages linked successfully). I guess I'd better adopt "multiple-environment" approach...

**Comment by dopplershift** [comment]
To be clear, you can use environments with anaconda as well.

**Comment by ocefpaf** [comment]
> To be clear, you can use environments with anaconda as well.

Indeed you can but I encourage miniconda because it discourages the use of
the root env due to the reduced set of pre-installed pkgs.

**Comment by dennissergeev** [comment]
Thanks, @dopplershift !

> Indeed you can but I encourage miniconda because it discourages the use of
the root env due to the reduced set of pre-installed pkgs.

What if I create say a dozen of very similar environments? Will it take the proportional amount of disc space?

**Comment by ocefpaf** [comment]
I believe that conda does not copy, only symlinks, but @msarahan knows
better.

**Comment by mmngreco** [comment]
Before, I had geopandas installing correctly, after an update stopped working. Now, even if I make a new environment, I can not make it work.

**Comment by msarahan** [comment]
Conda has the following default behavior:

1. try hardlinking
2. try softlinking
3. try copying

You should see what it is trying to do in the log output.  If it is falling
back to symlinking or copying, you should see that next to the package name
information.
