### ISSUE TITLE
Dependency resolution causes invalid installation

### ISSUE THREAD

**Issue by sdc50** [conda-forge/fiona-feedstock#55]
Currently installing fiona from conda-forge results in a mis-match in the dependency chain. For some reason some of the dependencies are installed from conda-forge and some are installed from the defaults channel. Specifically the conflict to be with libnetcdf and libgdal.

```
(test) $ conda install -c conda-forge --override-channels fiona
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /anaconda/envs/test:

The following NEW packages will be INSTALLED:

    click:         6.7-py35_0            conda-forge
    click-plugins: 1.0.3-py35_0          conda-forge
    cligj:         0.4.0-py35_0          conda-forge
    curl:          7.54.1-0              conda-forge
    fiona:         1.7.9-py35_1          conda-forge
    gdal:          2.1.0-py35_0                     
    geos:          3.5.1-1               conda-forge
    geotiff:       1.4.1-0                          
    hdf4:          4.2.12-0              conda-forge
    hdf5:          1.8.17-11             conda-forge
    icu:           58.1-1                conda-forge
    intel-openmp:  2018.0.0-hdd0ccc9_7              
    jpeg:          9b-1                  conda-forge
    kealib:        1.4.6-3               conda-forge
    krb5:          1.14.2-0              conda-forge
    libgdal:       2.1.0-0                          
    libgfortran:   3.0.1-h93005f0_2                 
    libnetcdf:     4.4.1-0               conda-forge
    libssh2:       1.8.0-1               conda-forge
    libtiff:       4.0.6-7               conda-forge
    mkl:           2018.0.0-hc285769_4              
    munch:         2.2.0-py35_0          conda-forge
    numpy:         1.13.3-py35hfd7066c_0            
    proj4:         4.9.2-0                          
    shapely:       1.6.1-py35_1          conda-forge
    six:           1.11.0-py35_1         conda-forge
    xerces-c:      3.1.4-3               conda-forge

Proceed ([y]/n)? y

(test) $ python -c "import fiona"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/anaconda/envs/test/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/anaconda/envs/test/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: dlopen(/anaconda/envs/test/lib/python3.5/site-packages/fiona/ogrext.cpython-35m-darwin.so, 2): Library not loaded: @rpath/libnetcdf.11.dylib
  Referenced from: /anaconda/envs/test/lib/libgdal.20.dylib
  Reason: Incompatible library version: libgdal.20.dylib requires version 12.0.0 or later, but libnetcdf.11.dylib provides version 11.0.0
```
It appears that if gdal is pinned to 2.1.2 or higher then the dependency resolution works out consistently:

```
(test) $ conda install -c conda-forge gdal=2.1.2 fiona
```
@dharhas, @ocefpaf, @msarahan: There is definitely a problem with the GDAL feedstock since 2.1.0 and 2.1.1 cannot be installed, but it seems like fiona could be more open in it's dependency (say gdal=2.1*) so it isn't trying to install 2.1.0 by default.

**Comment by ocefpaf** [comment]
My guess is that conda is getting confused by some pre-existing packages from your anaconda installation.
I have minconda and I get the right packages when issuing that command. You can probably have the same combination of packages if you try to create a new env instead of just issuing the command.

Can you try `$conda create -n test_fiona --channel conda-forge --override-channels fiona` ?

Here is what you should get:

```
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/filipe/miniconda3/envs/test_fiona:

The following NEW packages will be INSTALLED:

    boost:           1.64.0-py36_4         conda-forge
    boost-cpp:       1.64.0-1              conda-forge
    bzip2:           1.0.6-1               conda-forge
    ca-certificates: 2017.7.27.1-0         conda-forge
    cairo:           1.14.6-4              conda-forge
    certifi:         2017.7.27.1-py36_0    conda-forge
    click:           6.7-py36_0            conda-forge
    click-plugins:   1.0.3-py36_0          conda-forge
    cligj:           0.4.0-py36_0          conda-forge
    curl:            7.54.1-0              conda-forge
    expat:           2.1.0-3               conda-forge
    fiona:           1.7.9-py36_1          conda-forge
    fontconfig:      2.12.1-4              conda-forge
    freetype:        2.7-1                 conda-forge
    freexl:          1.0.2-2               conda-forge
    gdal:            2.1.4-py36_1          conda-forge
    geos:            3.5.1-1               conda-forge
    gettext:         0.19.7-1              conda-forge
    giflib:          5.1.4-0               conda-forge
    glib:            2.51.4-0              conda-forge
    hdf4:            4.2.12-0              conda-forge
    hdf5:            1.8.18-1              conda-forge
    icu:             58.1-1                conda-forge
    intel-openmp:    2018.0.0-h15fc484_7   defaults   
    jpeg:            9b-1                  conda-forge
    json-c:          0.12.1-0              conda-forge
    kealib:          1.4.7-3               conda-forge
    krb5:            1.14.2-0              conda-forge
    libdap4:         3.18.3-2              conda-forge
    libffi:          3.2.1-3               conda-forge
    libgdal:         2.1.4-3               conda-forge
    libgfortran:     3.0.0-1               defaults   
    libiconv:        1.14-4                conda-forge
    libkml:          1.3.0-1               conda-forge
    libnetcdf:       4.4.1.1-6             conda-forge
    libpng:          1.6.28-1              conda-forge
    libpq:           9.6.3-0               conda-forge
    libspatialite:   4.3.0a-15             conda-forge
    libssh2:         1.8.0-1               conda-forge
    libtiff:         4.0.7-0               conda-forge
    libxml2:         2.9.5-0               conda-forge
    mkl:             2018.0.0-hb491cac_4   defaults   
    munch:           2.2.0-py36_0          conda-forge
    ncurses:         5.9-10                conda-forge
    numpy:           1.13.3-py36ha12f23b_0 defaults   
    openjpeg:        2.1.2-3               conda-forge
    openssl:         1.0.2l-0              conda-forge
    pcre:            8.39-0                conda-forge
    pip:             9.0.1-py36_0          conda-forge
    pixman:          0.34.0-0              conda-forge
    poppler:         0.52.0-2              conda-forge
    poppler-data:    0.4.7-0               conda-forge
    proj4:           4.9.3-4               conda-forge
    python:          3.6.3-0               conda-forge
    readline:        6.2-0                 conda-forge
    setuptools:      36.3.0-py36_0         conda-forge
    shapely:         1.6.1-py36_1          conda-forge
    six:             1.11.0-py36_1         conda-forge
    sqlite:          3.13.0-1              conda-forge
    tk:              8.5.19-2              conda-forge
    util-linux:      2.21-0                defaults   
    wheel:           0.30.0-py_1           conda-forge
    xerces-c:        3.1.4-3               conda-forge
    xz:              5.2.3-0               conda-forge
    zlib:            1.2.8-3               conda-forge
```

**Comment by sdc50** [comment]
I can confirm that creating a new environment in the same command as installing fiona from conda-forge does work with Python 2.7, 3.5, and 3.6 (although I should have noted that I wasn't having the issue with Python 3.6). The issue only happens when I set up a new environment first (not using conda-forge) and then install fiona: 

```
$ conda create -n test_fiona python=3.5
Fetching package metadata ...........
Solving package specifications: .

Package plan for installation in environment /anaconda/envs/test_fiona:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.08.26-ha1e5d58_0     
    certifi:         2017.7.27.1-py35h0fdde5e_0
    libcxx:          4.0.1-h579ed51_0          
    libcxxabi:       4.0.1-hebd6815_0          
    libedit:         3.1-hb4e282d_0            
    libffi:          3.2.1-hd939716_3          
    ncurses:         6.0-ha932d30_1            
    openssl:         1.0.2l-h57f3a61_2         
    pip:             9.0.1-py35he52dd69_3      
    python:          3.5.4-hb8880cc_19         
    readline:        7.0-h81b24a6_3            
    setuptools:      36.5.0-py35h52cde6a_0     
    sqlite:          3.20.1-h900c3b0_1         
    tk:              8.6.7-hcdce994_1          
    wheel:           0.29.0-py35ha7aa5c4_1     
    xz:              5.2.3-ha24016e_1          
    zlib:            1.2.11-h60db283_1         

Proceed ([y]/n)? y

#
# To activate this environment, use:
# > source activate test_fiona
#
# To deactivate an active environment, use:
# > source deactivate
#

$ . activate test_fiona
(test_fiona) $ conda install -c conda-forge fiona
```
So something about the initial packages that get installed when creating an environment is throwing off the dependency solver.

**Comment by sdc50** [comment]
However, trying to isolate the problem, I still get the same issue when trying to install just gdal=2.1.0:

```
$conda create -n test_gdal -c conda-forge --override-channels python=3.5 gdal=2.1.0
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /anaconda/envs/test_gdal:

The following NEW packages will be INSTALLED:

    ca-certificates: 2017.7.27.1-0         conda-forge
    certifi:         2017.7.27.1-py35_0    conda-forge
    curl:            7.54.1-0              conda-forge
    gdal:            2.1.0-py35_0                     
    geos:            3.5.1-1               conda-forge
    geotiff:         1.4.1-0                          
    hdf4:            4.2.12-0              conda-forge
    hdf5:            1.8.17-11             conda-forge
    icu:             58.1-1                conda-forge
    intel-openmp:    2018.0.0-hdd0ccc9_7              
    jpeg:            9b-1                  conda-forge
    kealib:          1.4.6-3               conda-forge
    krb5:            1.14.2-0              conda-forge
    libgdal:         2.1.0-0                          
    libgfortran:     3.0.1-h93005f0_2                 
    libnetcdf:       4.4.1-0               conda-forge
    libssh2:         1.8.0-1               conda-forge
    libtiff:         4.0.7-0               conda-forge
    mkl:             2018.0.0-hc285769_4              
    ncurses:         5.9-10                conda-forge
    numpy:           1.13.3-py35hfd7066c_0            
    openssl:         1.0.2l-0              conda-forge
    pip:             9.0.1-py35_0          conda-forge
    proj4:           4.9.2-0                          
    python:          3.5.4-0               conda-forge
    readline:        6.2-0                 conda-forge
    setuptools:      36.3.0-py35_0         conda-forge
    sqlite:          3.13.0-1              conda-forge
    tk:              8.5.19-2              conda-forge
    wheel:           0.30.0-py_1           conda-forge
    xerces-c:        3.1.4-3               conda-forge
    xz:              5.2.3-0               conda-forge
    zlib:            1.2.8-3               conda-forge

Proceed ([y]/n)? 
```

**Comment by ocefpaf** [comment]
> So something about the initial packages that get installed when creating an environment is throwing off the dependency solver.

Yep. That is known and that is why we recommend `miniconda` and envs. See https://conda-forge.org/docs/conda-forge_gotchas.html#using-multiple-channels

> However, trying to isolate the problem, I still get the same issue when trying to install just gdal=2.1.0

`gdal 2.1.0` is too old and we won't fix any dependency issue with that. I recommend you to use `gdal 2.1.4` which is up-to-date and has full backward compatibility with any 2.1.x series.

**Comment by sdc50** [comment]
Thanks for the quick feedback.
