### ISSUE TITLE
Error importing fiona on python 3.5 due to kealib not found

### ISSUE THREAD

**Issue by willu47** [conda-forge/fiona-feedstock#86]
I'm installing fiona on TravisCI and getting errors due to a missing kealib version 1.4.7 (1.4.8 is being installed).  This error only occurs on Python 3.5 - my Python 3.6 build works perfectly well.

```python
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 372, in _getconftestmodules
    return self._path2confmods[path]
KeyError: local('/home/travis/build/nismod/smif/tests')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 403, in _importconftest
    return self._conftestpath2mod[conftestpath]
KeyError: local('/home/travis/build/nismod/smif/tests/conftest.py')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/_pytest/config/__init__.py", line 409, in _importconftest
    mod = conftestpath.pyimport()
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/py/_path/local.py", line 668, in pyimport
    __import__(modname)
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/_pytest/assertion/rewrite.py", line 226, in load_module
    py.builtin.exec_(co, mod.__dict__)
  File "/home/travis/build/nismod/smif/tests/conftest.py", line 23, in <module>
    from smif.data_layer import DatafileInterface
  File "/home/travis/build/nismod/smif/src/smif/data_layer/__init__.py", line 8, in <module>
    from smif.data_layer.datafile_interface import DatafileInterface
  File "/home/travis/build/nismod/smif/src/smif/data_layer/datafile_interface.py", line 9, in <module>
    import fiona
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/fiona/__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "/home/travis/miniconda/envs/testenv/lib/python3.5/site-packages/fiona/collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: libkea.so.1.4.7: cannot open shared object file: No such file or directory
ERROR: could not load /home/travis/build/nismod/smif/tests/conftest.py
```

See [this build](https://travis-ci.org/nismod/smif/jobs/407998276) for example.

**Comment by ocefpaf** [comment]
https://github.com/conda-forge/fiona-feedstock/pull/85 may fix this but we need to wait for the new binaries to be up in the channel.

**Comment by willu47** [comment]
Thanks for your efforts @ocefpaf! Looks frustrating...

**Comment by ocefpaf** [comment]
Indeed. I'm probably going to spend the whole day on this. For now I recommend using python 3.6 as a workaround.

**Comment by willu47** [comment]
Thanks, will do.
