### ISSUE TITLE
trouble installing fiona on windows

### ISSUE THREAD

**Issue by gboeing** [conda-forge/fiona-feedstock#89]
Issue:

Installed fiona with conda-forge in a new virtual environment. Importing it results in an error.

```
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Anaconda\envs\FIONA\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "c:\Anaconda\envs\FIONA\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
```

<br/>
Environment (<code>conda list</code>):
<details>

```

# packages in environment at c:\Anaconda\envs\FIONA:
#
# Name                    Version                   Build  Channel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
click                     6.7                        py_1    conda-forge
click-plugins             1.0.3                      py_1    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
curl                      7.61.0               h7602738_0  
expat                     2.2.5                he025d50_1    conda-forge
fiona                     1.7.13           py36h2fc6367_2    conda-forge
freexl                    1.0.5                hd288d7e_1    conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geos                      3.6.2                he025d50_2    conda-forge
geotiff                   1.4.2                h2080a26_2    conda-forge
hdf4                      4.2.13               h712560f_2  
hdf5                      1.10.2               hbc3b0e7_1    conda-forge
icc_rt                    2017.0.4             h97af966_0  
intel-openmp              2018.0.3                      0  
jpeg                      9c                   hfa6e2cd_0    conda-forge
kealib                    1.4.9                h4380d0d_2    conda-forge
libcurl                   7.61.0               h7602738_0  
libgdal                   2.2.4                hf00ed0c_6    conda-forge
libiconv                  1.15                 hfa6e2cd_1    conda-forge
libnetcdf                 4.6.1                h183b1a9_3    conda-forge
libpng                    1.6.35               h7602738_0    conda-forge
libpq                     9.6.6                h14f23c8_0  
libspatialite             4.3.0a              h582a839_21    conda-forge
libssh2                   1.8.0                hc4dcbb0_2    conda-forge
libtiff                   4.0.9                hf1753bf_1    conda-forge
libxml2                   2.9.8                haffccfe_2    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.5                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
munch                     2.3.2                      py_0    conda-forge
numpy                     1.14.3           py36h9fa60d3_2  
numpy-base                1.14.3           py36h5c71026_0  
openjpeg                  2.3.0                h25a6d84_3    conda-forge
openssl                   1.0.2o               hfa6e2cd_1    conda-forge
pip                       18.0                     py36_1    conda-forge
proj4                     4.9.3                hcf24537_7  
python                    3.6.6                he025d50_0    conda-forge
setuptools                40.0.0                   py36_1    conda-forge
shapely                   1.6.4            py36hc90234e_1    conda-forge
six                       1.11.0                   py36_1    conda-forge
sqlite                    3.24.0               hb652765_0    conda-forge
vc                        14.1                 h0510ff6_3  
vs2015_runtime            15.5.2                        3  
wheel                     0.31.1                   py36_1    conda-forge
wincertstore              0.2                      py36_2    conda-forge
xerces-c                  3.2.0                h44c76bb_2  
xz                        5.2.4                h2fa13f4_0    conda-forge
zlib                      1.2.11               h2fa13f4_3    conda-forge

```

</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : FIONA
    active env location : c:\Anaconda\envs\FIONA
            shell level : 1
       user config file : C:\Users\Geoff\.condarc
 populated config files : C:\Users\Geoff\.condarc
          conda version : 4.5.9
    conda-build version : not installed
         python version : 3.6.5.final.0
       base environment : c:\Anaconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : c:\Anaconda\pkgs
                          C:\Users\Geoff\AppData\Local\conda\conda\pkgs
       envs directories : c:\Anaconda\envs
                          C:\Users\Geoff\AppData\Local\conda\conda\envs
                          C:\Users\Geoff\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/3.6.5 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by gboeing** [comment]
This is a GDAL problem. Resolved as described in https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-410577468

**Comment by gboeing** [comment]
cross-reference https://github.com/conda/conda/issues/7626

**Comment by ocefpaf** [comment]
@gboeing we are now recommending people to use `conda-forge` or `defaults`, but not both, strictly until https://github.com/conda/conda/issues/7656 is addressed.

BTW, if you can give +1 on that issue it would help bump its priority :grimacing:

**Comment by gboeing** [comment]
@ocefpaf thanks, just gave +1 on that issue.
