### ISSUE TITLE
DLL not loading on Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/fiona-feedstock#91]
Issue:

I saw this here first: https://github.com/conda-forge/staged-recipes/pull/6422

It also fails locally on Windows:
```
(base) C:\Users\Jason Moore\Documents>conda install fiona
Solving environment: done

## Package Plan ##

  environment location: C:\ProgramData\Anaconda3

  added / updated specs:
    - fiona


The following NEW packages will be INSTALLED:

    blosc:          1.14.4-h6538335_0     conda-forge
    click-plugins:  1.0.3-py_1            conda-forge
    cligj:          0.4.0-py36_0          conda-forge
    expat:          2.2.5-he025d50_1      conda-forge
    fiona:          1.7.13-py36h2fc6367_3 conda-forge
    freexl:         1.0.5-hd288d7e_1      conda-forge
    gdal:           2.2.4-py36h2fc6367_1  conda-forge
    geos:           3.6.2-he025d50_2      conda-forge
    geotiff:        1.4.2-h2080a26_2      conda-forge
    hdf4:           4.2.13-h712560f_2
    kealib:         1.4.9-h4380d0d_2      conda-forge
    libcurl:        7.61.0-h7602738_0
    libgdal:        2.2.4-hf00ed0c_6      conda-forge
    libnetcdf:      4.6.1-ha2173a7_4      conda-forge
    libpq:          10.4-h5fe2233_0
    libspatialite:  4.3.0a-h582a839_21    conda-forge
    munch:          2.3.2-py_0            conda-forge
    openjpeg:       2.3.0-h25a6d84_3      conda-forge
    proj4:          4.9.3-hcf24537_7
    pyreadline:     2.1-py36_0            conda-forge
    shapely:        1.6.4-py36hc90234e_1  conda-forge
    xerces-c:       3.2.0-h44c76bb_2
    xz:             5.2.4-h2fa13f4_1      conda-forge

The following packages will be UPDATED:

    bzip2:          1.0.6-vc14_1          conda-forge [vc14] --> 1.0.6-hfa6e2cd_2        conda-forge
    conda:          4.5.4-py36_0          conda-forge --> 4.5.9-py36_0            conda-forge
    curl:           7.55.1-vc14_0         conda-forge [vc14] --> 7.61.0-h7602738_0
    freetype:       2.8.1-vc14_0          conda-forge [vc14] --> 2.8.1-ha63716d_1        conda-forge
    h5py:           2.7.0-py36hfbe0a52_1              --> 2.8.0-py36hb24199d_1    conda-forge
    hdf5:           1.10.1-vc14_2         conda-forge [vc14] --> 1.10.2-hbc3b0e7_1       conda-forge
    icu:            58.2-vc14_0           conda-forge [vc14] --> 58.2-ha66f8fd_1
    jpeg:           9b-vc14_2             conda-forge [vc14] --> 9c-hfa6e2cd_0           conda-forge
    krb5:           1.14.6-vc14_0         conda-forge [vc14] --> 1.16.1-h038dc86_0       conda-forge
    libiconv:       1.14-vc14_4           conda-forge [vc14] --> 1.15-hfa6e2cd_1         conda-forge
    libpng:         1.6.34-vc14_0         conda-forge [vc14] --> 1.6.35-h7602738_0       conda-forge
    libssh2:        1.8.0-vc14_2          conda-forge [vc14] --> 1.8.0-hc4dcbb0_2        conda-forge
    libtiff:        4.0.9-vc14_0          conda-forge [vc14] --> 4.0.9-hf1753bf_1        conda-forge
    libxml2:        2.9.5-vc14_1          conda-forge [vc14] --> 2.9.8-haffccfe_2        conda-forge
    libxslt:        1.1.32-vc14_0         conda-forge [vc14] --> 1.1.32-h5632236_1       conda-forge
    lzo:            2.10-vc14_0           conda-forge [vc14] --> 2.10-h6df0209_2
    openssl:        1.0.2o-vc14_0         conda-forge [vc14] --> 1.0.2o-hfa6e2cd_1       conda-forge
    pycurl:         7.43.0-py36h086bf4c_3             --> 7.43.0.2-py36h74b6da3_0
    pytables:       3.4.2-py36h71138e3_2              --> 3.4.4-py36h7e76658_1    conda-forge
    qt:             5.6.2-vc14_1          conda-forge [vc14] --> 5.6.2-h2639256_8        conda-forge
    sqlite:         3.22.0-vc14_0         conda-forge [vc14] --> 3.24.0-hb652765_0       conda-forge
    tk:             8.6.7-vc14_0          conda-forge [vc14] --> 8.6.7-hcb92d03_3
    vc:             14-h2379b0c_2                     --> 14.1-h0510ff6_3
    vs2015_runtime: 14.0.25123-hd4c4e62_2             --> 15.5.2-3
    yaml:           0.1.7-vc14_0          conda-forge [vc14] --> 0.1.7-hfa6e2cd_1        conda-forge
    zlib:           1.2.11-vc14_0         conda-forge [vc14] --> 1.2.11-h2fa13f4_3       conda-forge

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(base) C:\Users\Jason Moore\Documents>python
Python 3.6.3 |Anaconda custom (64-bit)| (default, Nov  8 2017, 15:10:56) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import fiona
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\__init__.py", line 69, in <module>
    from fiona.collection import Collection, BytesCollection, vsi_path
  File "C:\ProgramData\Anaconda3\lib\site-packages\fiona\collection.py", line 9, in <module>
    from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
ImportError: DLL load failed: The specified module could not be found.
>>>
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

(base) C:\Users\Jason Moore\Documents>conda list
# packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
alabaster                 0.7.10           py36hcd07829_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.5            py36hd36550c_0
anaconda-navigator        1.6.9            py36hc720852_0
anaconda-project          0.8.0            py36h8b3bf89_0
asn1crypto                0.22.0           py36h8e79faa_1
astroid                   1.5.3            py36h9d85297_0
astropy                   2.0.2            py36h06391c4_4
babel                     2.5.0            py36h35444c1_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
beautifulsoup4            4.6.0            py36hd4cc5e8_1
bitarray                  0.8.1            py36h6af124b_0
bkcharts                  0.2              py36h7e685f7_0
blaze                     0.11.3           py36h8a29ca5_0
bleach                    2.0.0            py36h0a7e3d6_0
blosc                     1.14.4               h6538335_0    conda-forge
bokeh                     0.12.10          py36h0be3b39_0
boto                      2.48.0           py36h1a776d2_1
bottleneck                1.2.1            py36hd119dfa_0
bzip2                     1.0.6                hfa6e2cd_2    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
cachecontrol              0.12.3           py36hfe50d7b_0
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.10.0           py36hae3d1b5_1
chardet                   3.0.4            py36h420ce6e_1
click                     6.7              py36hec8c647_0
click-plugins             1.0.3                      py_1    conda-forge
cligj                     0.4.0                    py36_0    conda-forge
cloudpickle               0.5.2            py36h6b1d831_0
clyent                    1.2.2            py36hb10d595_1
colorama                  0.3.9            py36h029ae33_0
comtypes                  1.1.2            py36heb9b3d1_0
conda                     4.5.9                    py36_0    conda-forge
conda-build               3.0.30           py36he296fd2_0
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0            py36h065de53_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.0.3            py36h123decb_1
curl                      7.61.0               h7602738_0
cycler                    0.10.0           py36h009560c_0
cython                    0.26.1           py36h18049ac_0
cytoolz                   0.8.2            py36h547e66e_0
dash                      0.21.1                     py_1    conda-forge
dash-core-components      0.22.1                     py_0    conda-forge
dash-html-components      0.10.1                     py_0    conda-forge
dash-renderer             0.12.1                     py_1    conda-forge
dask                      0.16.0           py36hea4f2f0_0
dask-core                 0.16.0           py36h5683b08_0
datashape                 0.5.4            py36h5770b85_0
decorator                 4.1.2            py36he63a57b_0
distlib                   0.2.5            py36h51371be_0
distributed               1.20.0           py36h2fcf393_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
et_xmlfile                1.0.1            py36h3d2d736_0
expat                     2.2.5                he025d50_1    conda-forge
fastcache                 1.0.2            py36hffdae1b_0
filelock                  2.0.13           py36h20000bf_0
fiona                     1.7.13           py36h2fc6367_3    conda-forge
flask                     0.12.2           py36h98b5e8f_0
flask-compress            1.4.0                      py_0    conda-forge
flask-cors                3.0.3            py36h8a3855d_0
freetype                  2.8.1                ha63716d_1    conda-forge
freexl                    1.0.5                hd288d7e_1    conda-forge
gdal                      2.2.4            py36h2fc6367_1    conda-forge
geos                      3.6.2                he025d50_2    conda-forge
geotiff                   1.4.2                h2080a26_2    conda-forge
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
glob2                     0.6              py36hdf76b57_0
greenlet                  0.4.12           py36ha00ad21_0
h5py                      2.8.0            py36hb24199d_1    conda-forge
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.2               hbc3b0e7_1    conda-forge
heapdict                  1.0.0            py36h21fa5f4_0
html5lib                  0.999999999      py36ha09b1f3_0
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                 ha66f8fd_1
idna                      2.6              py36h148d497_1
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1            py36he29f638_0
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.6.1            py36hbb77b34_0
ipython                   6.2.1            py36h9cf0123_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.0.5            py36h6314756_0
isort                     4.2.15           py36h6198cc5_0
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3              py36h64a5255_0
jedi                      0.10.2           py36hed927a0_0
jinja2                    2.9.6            py36h10aa3a0_1
jpeg                      9c                   hfa6e2cd_0    conda-forge
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0            py36h422fd7e_2
jupyter_client            5.1.0            py36h9902a9a_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.4.0            py36h56e9d50_0
jupyterlab                0.27.0           py36h34cc53b_2
jupyterlab_launcher       0.4.0            py36h22c3ccf_0
kealib                    1.4.9                h4380d0d_2    conda-forge
krb5                      1.16.1               h038dc86_0    conda-forge
lazy-object-proxy         1.3.1            py36hd1c21d2_0
libcurl                   7.61.0               h7602738_0
libgdal                   2.2.4                hf00ed0c_6    conda-forge
libiconv                  1.15                 hfa6e2cd_1    conda-forge
libnetcdf                 4.6.1                ha2173a7_4    conda-forge
libpng                    1.6.35               h7602738_0    conda-forge
libpq                     10.4                 h5fe2233_0
libspatialite             4.3.0a              h582a839_21    conda-forge
libssh2                   1.8.0                hc4dcbb0_2    conda-forge
libtiff                   4.0.9                hf1753bf_1    conda-forge
libxml2                   2.9.8                haffccfe_2    conda-forge
libxslt                   1.1.32               h5632236_1    conda-forge
llvmlite                  0.20.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      4.1.0            py36h0dcd83c_0
lzo                       2.10                 h6df0209_2
markupsafe                1.0              py36h0e26971_1
matplotlib                2.1.0            py36h11b4b9c_0
mccabe                    0.6.1            py36hb41005a_1
menuinst                  1.4.10           py36h42196fb_0
mistune                   0.8.1            py36h007b88b_0
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py36h57e144c_4
mpmath                    0.19             py36he326802_2
msgpack-python            0.4.8            py36h58b1e9d_0
multipledispatch          0.4.9            py36he44c36e_0
munch                     2.3.2                      py_0    conda-forge
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.0              py36hff991e3_0
nltk                      3.2.5            py36h76d52bb_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.2.1            py36h4fb2ca6_0
numba                     0.35.0             np113py36_10
numexpr                   2.6.2            py36h514de0f_2
numpy                     1.13.3           py36ha320f96_0
numpydoc                  0.7.0            py36ha25429e_0
odo                       0.5.1            py36h7560279_0
olefile                   0.44             py36h0a7bdd2_0
openjpeg                  2.3.0                h25a6d84_3    conda-forge
openpyxl                  2.4.8            py36hf3b77f6_1
openssl                   1.0.2o               hfa6e2cd_1    conda-forge
packaging                 16.8             py36ha0986f6_1
pandas                    0.21.0           py36he09d4dd_1
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
partd                     0.3.8            py36hc8e763b_0
path.py                   10.3.1           py36h3dd8b46_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.4.1            py36h42cefec_0
pep8                      1.7.0            py36h0f3d67a_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    4.2.1            py36hdb25ab2_0
pip                       9.0.1            py36h226ae91_4
pkginfo                   1.4.1            py36hb0f9cfa_1
plotly                    2.5.1                    py36_0    conda-forge
ply                       3.10             py36h1211beb_0
progress                  1.3              py36hbeca8d3_0
proj4                     4.9.3                hcf24537_7
prompt_toolkit            1.0.15           py36h60b8f86_0
psutil                    5.4.0            py36h4e662fb_0
py                        1.4.34           py36ha4aca3a_1
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1            py36he68e6e2_1
pycurl                    7.43.0.2         py36h74b6da3_0
pyflakes                  1.6.0            py36h0b975d6_0
pygments                  2.2.0            py36hb010967_0
pylint                    1.7.4            py36ha4e6ded_0
pyodbc                    4.0.17           py36h0006bc2_0
pyopenssl                 17.2.0           py36h15ca2fc_0
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pyreadline                2.1                      py36_0    conda-forge
pysocks                   1.6.7            py36h698d350_1
pytables                  3.4.4            py36h7e76658_1    conda-forge
pytest                    3.2.1            py36h753b05e_1
python                    3.6.3                h3b118a2_4
python-dateutil           2.6.1            py36h509ddcb_1
pytz                      2017.3           py36h1d3fa6b_0
pywavelets                0.5.2            py36hc649158_0
pywin32                   221              py36h9c10281_0
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.2           py36h38c27d9_2
qt                        5.6.2                h2639256_8    conda-forge
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
requests                  2.18.4           py36h4371aae_1
rope                      0.10.5           py36hcaf5641_0
ruamel_yaml               0.11.14          py36h9b16331_2
scikit-image              0.13.0           py36h6dffa3f_1
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
seaborn                   0.8.1            py36h9b69545_0
setuptools                36.5.0           py36h65f9e6e_0
shapely                   1.6.4            py36hc90234e_1    conda-forge
simplegeneric             0.8.1            py36heab741f_0
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
skijumpdesign             1.2.0                      py_1    conda-forge
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.7            py36ha90ac20_0
sphinx                    1.6.3            py36h9bb690b_0
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1
spyder                    3.2.4            py36h8845eaa_0
sqlalchemy                1.1.13           py36h5948d12_0
sqlite                    3.24.0               hb652765_0    conda-forge
statsmodels               0.8.0            py36h6189b4c_0
sympy                     1.1.1            py36h96708e0_0
tblib                     1.3.2            py36h30f5020_0
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7                hcb92d03_3
toolz                     0.8.2            py36he152a52_0
tornado                   4.5.2            py36h57f6048_0
traitlets                 4.3.2            py36h096827d_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
urllib3                   1.22             py36h276f60a_0
vc                        14.1                 h0510ff6_3
vs2015_runtime            15.5.2                        3
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.12.2           py36h866a736_0
wheel                     0.30.0           py36h6c3ec14_1
widgetsnbextension        3.0.2            py36h364476f_1
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36he5f5981_0
xerces-c                  3.2.0                h44c76bb_2
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                1.0.2            py36hf723b7d_0
xlwings                   0.11.4           py36hd3cf94d_0
xlwt                      1.3.0            py36h1a4751e_0
xz                        5.2.4                h2fa13f4_1    conda-forge
yaml                      0.1.7                hfa6e2cd_1    conda-forge
zict                      0.1.3            py36h2d8e73e_0
zlib                      1.2.11               h2fa13f4_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(base) C:\Users\Jason Moore\Documents>conda info

     active environment : base
    active env location : C:\ProgramData\Anaconda3
            shell level : 1
       user config file : C:\Users\Jason Moore\.condarc
 populated config files : C:\Users\Jason Moore\.condarc
          conda version : 4.5.9
    conda-build version : 3.0.30
         python version : 3.6.3.final.0
       base environment : C:\ProgramData\Anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\Jason Moore\AppData\Local\conda\conda\pkgs
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\Jason Moore\AppData\Local\conda\conda\envs
                          C:\Users\Jason Moore\.conda\envs
               platform : win-64
             user-agent : conda/4.5.9 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.17134
          administrator : True
             netrc file : None
           offline mode : False


(base) C:\Users\Jason Moore\Documents>
```
</details>

**Comment by ocefpaf** [comment]
"conda install" on an existing env with packages already installed never worked the way one expected, note the amount of packages from `defatuls` you got there.

Please take a look at: 

https://conda-forge.org/docs/conda-forge_gotchas.html

and

https://github.com/conda-forge/fiona-feedstock/issues/89

Ping @kalefranz and @msarahan for awareness. This kind of issue would be "easier" to deal under the scenarios described in https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-409234067

**Comment by moorepants** [comment]
Note that this failed first on a stage-recipe, which doesn't have a huge base env. I only verfied it on my Windows computer.

**Comment by ocefpaf** [comment]
Yep. From https://github.com/conda-forge/gdal-feedstock/issues/219#issuecomment-409234067 you can get more of the big picture but until a new conda that fixes the issue with feature everything is pretty much broken on Windows.

**Comment by msarahan** [comment]
xref https://github.com/conda/conda/issues/7626
